"""Data classification for backup (BAK-001).

**What you choose not to back up matters as much as what you do.** Backing up
a rebuildable read model buys nothing and costs restore time; backing up a
rate-limit counter restores yesterday's abuse budget. So every table in the
platform is classified, and the classification is derived from what the
platform already knows about itself rather than hand-maintained.

| Class | Meaning | On loss |
| --- | --- | --- |
| `critical` | Business truth; cannot be reconstructed | Money and trust are lost |
| `important` | Operational state; painful but survivable | Degraded service, no data loss |
| `rebuildable` | Derived from something else the platform holds | Rebuild it |
| `ephemeral` | Meaningful only right now | Let it go |

The interesting entries are the `rebuildable` ones. This platform holds a
durable event log (`event_outbox`) and guarantees every projection can be
reconstructed from it (BR-0015). That guarantee is what lets projection
tables be excluded from the critical set — a restore rebuilds them, and a
rebuilt projection is *provably* identical to an incrementally built one.

`consumer_cursor` and `consumer_execution` are the subtle case. They are not
business data, but restoring WITHOUT them would replay the whole event log
into consumers, sending every notification again. They are therefore
`important`: losing them is safe only if you deliberately reset the world.
"""

from dataclasses import dataclass

CRITICAL = "critical"
IMPORTANT = "important"
REBUILDABLE = "rebuildable"
EPHEMERAL = "ephemeral"

ORDER = {CRITICAL: 0, IMPORTANT: 1, REBUILDABLE: 2, EPHEMERAL: 3}


@dataclass(frozen=True)
class TableClass:
    table: str
    classification: str
    reason: str


# Tables whose loss destroys business truth. Everything not listed elsewhere
# defaults here — an unclassified table is treated as critical, because the
# safe default for "I don't know" is "keep it".
_IMPORTANT = {
    "auth_session": "sessions; losing them logs everyone out but loses nothing",
    "consumer_cursor": (
        "consumer position. Restoring without it replays the whole log into "
        "consumers — every notification sent again"
    ),
    "consumer_execution": (
        "idempotency ledger. It is what makes replay safe; losing it turns a "
        "restore into a duplicate-effects incident"
    ),
    "event_delivery": "per-attempt delivery audit; useful forensically, not business truth",
    "device_health_report": "last-known hardware state; re-reported on next contact",
    "password_reset_token": "short-lived one-time tokens; users can request another",
    "invitation": "pending invitations; re-issuable",
    "sync_operation": (
        "device replay ledger. Like consumer_execution, it prevents duplicate "
        "application of offline work"
    ),
    # DR-001: this was classified `rebuildable`, which excluded it from every
    # backup — and NOTHING REBUILDS IT. It is written once, by
    # MilkCollectionService.complete(), and is not a registered projection, so
    # a restore left it permanently empty. The recovery comparison caught it as
    # "reports: 2 in source, 0 restored".
    #
    # "Derived" and "rebuildable" are not the same claim. Derived says the
    # information exists elsewhere; rebuildable says there is CODE that will
    # reconstruct it. Only the second one makes it safe to discard, and the
    # test below now enforces exactly that distinction.
    "transaction_metrics": (
        "per-transaction timing and outcome counters. Derived in principle, "
        "but no rebuilder exists — so it must be backed up"
    ),
}

_REBUILDABLE = {
    "projection_daily_totals": "projection — rebuildable from the event log (BR-0015)",
    "projection_center_totals": "projection — rebuildable from the event log (BR-0015)",
    "projection_supplier_totals": "projection — rebuildable from the event log (BR-0015)",
    "notification_recipient": "recipient directory projection — rebuildable (BR-0015)",
    "projection_state": "projection bookkeeping; regenerated by a rebuild",
}

_EPHEMERAL: dict[str, str] = {
    # Nothing in PostgreSQL is ephemeral today. Rate limits and locks live in
    # Redis and are classified in the Redis section of BACKUP.md.
}

# Why each critical table matters, for the ones where it is not obvious.
_CRITICAL_REASONS = {
    "event_outbox": (
        "THE event log. Every projection and every consumer effect derives "
        "from it; it is the platform's source of truth for what happened"
    ),
    "audit_record": "immutable audit trail; required for dispute resolution and compliance",
    "payment": "money movement",
    "receipt": "immutable proof of payment; cannot be re-derived once the world moves on",
    "settlement": "what a supplier is owed",
    "milk_collection_transaction": "the collection record a farmer's payment derives from",
    "dead_letter_queue": "events that failed processing; replayable forever, so never discard",
}


def classify(table: str) -> TableClass:
    if table in _IMPORTANT:
        return TableClass(table, IMPORTANT, _IMPORTANT[table])
    if table in _REBUILDABLE:
        return TableClass(table, REBUILDABLE, _REBUILDABLE[table])
    if table in _EPHEMERAL:
        return TableClass(table, EPHEMERAL, _EPHEMERAL[table])
    return TableClass(
        table,
        CRITICAL,
        _CRITICAL_REASONS.get(table, "business record with no other source"),
    )


def classify_all() -> list[TableClass]:
    """Every mapped table, classified. Derived from the metadata so a new
    table is classified the moment it exists — as `critical` unless someone
    deliberately says otherwise.

    Registers every model first: `Base.metadata` is only as complete as the
    imports a process happens to have done, and a backup that silently
    captured one table because of that is exactly the bug CI-001 found.
    """
    from platform_core.core.db import Base
    from platform_core.core.model_registry import import_all_models

    import_all_models()
    return sorted(
        (classify(table.name) for table in Base.metadata.sorted_tables),
        key=lambda c: (ORDER[c.classification], c.table),
    )


def tables_for_backup(include_rebuildable: bool = False) -> list[str]:
    """What a backup captures.

    Rebuildable tables are excluded by default: capturing them costs restore
    time and buys nothing the event log cannot regenerate. `include_rebuildable`
    exists for the case where a faster restore matters more than a smaller
    backup — rebuilding a large projection can take minutes.

    **`rebuildable` is a claim about code, not about data.** Excluding a table
    here is only safe if something actually reconstructs it; DR-001 found a
    table marked rebuildable that nothing rebuilt, so a restore silently lost
    it. `rebuildable_tables_without_a_rebuilder()` is the guard, and a test
    fails the build if it ever returns a name.
    """
    keep = {CRITICAL, IMPORTANT} | ({REBUILDABLE} if include_rebuildable else set())
    return [c.table for c in classify_all() if c.classification in keep]


def rebuildable_tables_without_a_rebuilder() -> list[str]:
    """Tables excluded from backup that nothing can actually reconstruct.

    Must always be empty. A name here means a restore loses that table's
    contents permanently and silently — the backup skipped it on the promise
    that it could be regenerated, and no code keeps that promise.

    DR-001 found `transaction_metrics` in exactly this state.

    `projection_state` is the framework's own bookkeeping: it is written by
    the rebuild machinery rather than by a projection, so it is excluded from
    the check rather than exempted from the rule.
    """
    from platform_core.modules.event_relay.projections import (
        discover_projections,
        registered_projections,
    )

    discover_projections()
    rebuildable_by_code = {"projection_state"}
    for projection in registered_projections():
        for model in projection.models:
            rebuildable_by_code.add(model.__tablename__)

    return sorted(
        entry.table
        for entry in classify_all()
        if entry.classification == REBUILDABLE and entry.table not in rebuildable_by_code
    )
