"""LACTEVA-ADMIN-018 device make and model

WO-53. What the label on the machine says. The hardware discovery checklist
collects make and model for every instrument, and a per-model driver (D-16) is
selected by exactly that pair, so a registry that cannot record them is one a
connector cannot be built on.

Both NOT NULL with a SERVER default, not merely a Python one — the lesson from
LACTEVA-NOTIFY-003, where autogenerate wrote a bare NOT NULL, every SQLite test
passed, and the PostgreSQL proof failed on the first non-ORM insert.

Revision ID: 0e45ee1f7f13
Revises: e8edb960dcbe
Create Date: 2026-09-01 02:15:51.143904
"""

import sqlalchemy as sa
from alembic import op

revision = "0e45ee1f7f13"
down_revision = "e8edb960dcbe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device", sa.Column("make", sa.String(length=80), server_default="", nullable=False)
    )
    op.add_column(
        "device", sa.Column("model", sa.String(length=80), server_default="", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "model")
    op.drop_column("device", "make")
    # ### end Alembic commands ###
