"""milk collection transaction engine

Revision ID: 15471450e001
Revises: ad283b1e49b5
Create Date: 2026-08-03 00:59:59.085063
"""

import sqlalchemy as sa
from alembic import op

revision = "15471450e001"
down_revision = "ad283b1e49b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_session",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_by", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_session_center_id"), "collection_session", ["center_id"], unique=False
    )
    op.create_index(
        op.f("ix_collection_session_status"), "collection_session", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_collection_session_tenant_id"), "collection_session", ["tenant_id"], unique=False
    )
    op.create_table(
        "milk_collection_transaction",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("milk_type", sa.String(length=20), nullable=True),
        sa.Column("milk_type_custom", sa.String(length=60), nullable=True),
        sa.Column("container_type", sa.String(length=40), nullable=True),
        sa.Column("container_identifier", sa.String(length=80), nullable=True),
        sa.Column("arrival_temperature_c", sa.Float(), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("weight_unit", sa.String(length=8), nullable=True),
        sa.Column("gross_weight", sa.Float(), nullable=True),
        sa.Column("tare_weight", sa.Float(), nullable=True),
        sa.Column("net_weight", sa.Float(), nullable=True),
        sa.Column("weight_source", sa.String(length=20), nullable=True),
        sa.Column("fat", sa.Float(), nullable=True),
        sa.Column("snf", sa.Float(), nullable=True),
        sa.Column("clr", sa.Float(), nullable=True),
        sa.Column("density", sa.Float(), nullable=True),
        sa.Column("quality_temperature_c", sa.Float(), nullable=True),
        sa.Column("quality_remarks", sa.String(length=300), nullable=False),
        sa.Column("quality_source", sa.String(length=20), nullable=True),
        sa.Column("pricing_status", sa.String(length=30), nullable=True),
        sa.Column("rejected_reason", sa.String(length=300), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_reason", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_center_id"),
        "milk_collection_transaction",
        ["center_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_operator_id"),
        "milk_collection_transaction",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_session_id"),
        "milk_collection_transaction",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_state"),
        "milk_collection_transaction",
        ["state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_supplier_id"),
        "milk_collection_transaction",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_tenant_id"),
        "milk_collection_transaction",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "transaction_event",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id", "sequence", name="uq_txevent_tx_seq"),
    )
    op.create_index(
        op.f("ix_transaction_event_tenant_id"), "transaction_event", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_event_transaction_id"),
        "transaction_event",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "transaction_metrics",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("final_state", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_metrics_center_id"), "transaction_metrics", ["center_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_metrics_operator_id"),
        "transaction_metrics",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_metrics_session_id"),
        "transaction_metrics",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_metrics_supplier_id"),
        "transaction_metrics",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_metrics_tenant_id"), "transaction_metrics", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_metrics_transaction_id"),
        "transaction_metrics",
        ["transaction_id"],
        unique=True,
    )
    op.create_table(
        "transaction_snapshot",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_snapshot_tenant_id"),
        "transaction_snapshot",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_snapshot_transaction_id"),
        "transaction_snapshot",
        ["transaction_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_snapshot_transaction_id"), table_name="transaction_snapshot")
    op.drop_index(op.f("ix_transaction_snapshot_tenant_id"), table_name="transaction_snapshot")
    op.drop_table("transaction_snapshot")
    op.drop_index(op.f("ix_transaction_metrics_transaction_id"), table_name="transaction_metrics")
    op.drop_index(op.f("ix_transaction_metrics_tenant_id"), table_name="transaction_metrics")
    op.drop_index(op.f("ix_transaction_metrics_supplier_id"), table_name="transaction_metrics")
    op.drop_index(op.f("ix_transaction_metrics_session_id"), table_name="transaction_metrics")
    op.drop_index(op.f("ix_transaction_metrics_operator_id"), table_name="transaction_metrics")
    op.drop_index(op.f("ix_transaction_metrics_center_id"), table_name="transaction_metrics")
    op.drop_table("transaction_metrics")
    op.drop_index(op.f("ix_transaction_event_transaction_id"), table_name="transaction_event")
    op.drop_index(op.f("ix_transaction_event_tenant_id"), table_name="transaction_event")
    op.drop_table("transaction_event")
    op.drop_index(
        op.f("ix_milk_collection_transaction_tenant_id"), table_name="milk_collection_transaction"
    )
    op.drop_index(
        op.f("ix_milk_collection_transaction_supplier_id"), table_name="milk_collection_transaction"
    )
    op.drop_index(
        op.f("ix_milk_collection_transaction_state"), table_name="milk_collection_transaction"
    )
    op.drop_index(
        op.f("ix_milk_collection_transaction_session_id"), table_name="milk_collection_transaction"
    )
    op.drop_index(
        op.f("ix_milk_collection_transaction_operator_id"), table_name="milk_collection_transaction"
    )
    op.drop_index(
        op.f("ix_milk_collection_transaction_center_id"), table_name="milk_collection_transaction"
    )
    op.drop_table("milk_collection_transaction")
    op.drop_index(op.f("ix_collection_session_tenant_id"), table_name="collection_session")
    op.drop_index(op.f("ix_collection_session_status"), table_name="collection_session")
    op.drop_index(op.f("ix_collection_session_center_id"), table_name="collection_session")
    op.drop_table("collection_session")
    # ### end Alembic commands ###
