"""milk transaction pricing integration

Revision ID: 47434355bf8f
Revises: 86e2cdb89091
Create Date: 2026-08-04 00:43:05.430665
"""

import sqlalchemy as sa
from alembic import op

revision = "47434355bf8f"
down_revision = "86e2cdb89091"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "milk_collection_transaction",
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "milk_collection_transaction",
        sa.Column("gross_amount", sa.Numeric(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "milk_collection_transaction", sa.Column("currency", sa.String(length=3), nullable=True)
    )
    op.add_column(
        "milk_collection_transaction", sa.Column("calculation_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "milk_collection_transaction",
        sa.Column("pricing_detail", sa.String(length=300), nullable=True),
    )
    op.create_index(
        op.f("ix_milk_collection_transaction_calculation_id"),
        "milk_collection_transaction",
        ["calculation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_milk_collection_transaction_calculation_id"),
        table_name="milk_collection_transaction",
    )
    op.drop_column("milk_collection_transaction", "pricing_detail")
    op.drop_column("milk_collection_transaction", "calculation_id")
    op.drop_column("milk_collection_transaction", "currency")
    op.drop_column("milk_collection_transaction", "gross_amount")
    op.drop_column("milk_collection_transaction", "unit_price")
    # ### end Alembic commands ###
