"""collection center facilities

Revision ID: 5a89536bb4e7
Revises: 5856e2dbbd12
Create Date: 2026-08-03 00:08:21.417213
"""

import sqlalchemy as sa
from alembic import op

revision = "5a89536bb4e7"
down_revision = "5856e2dbbd12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "center_calendar_entry",
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("center_id", "day", name="uq_calendar_center_day"),
    )
    op.create_index(
        op.f("ix_center_calendar_entry_center_id"),
        "center_calendar_entry",
        ["center_id"],
        unique=False,
    )
    op.create_table(
        "center_operating_window",
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("opens", sa.Time(), nullable=False),
        sa.Column("closes", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("center_id", "day_of_week", "opens", name="uq_window_center_day_open"),
    )
    op.create_index(
        op.f("ix_center_operating_window_center_id"),
        "center_operating_window",
        ["center_id"],
        unique=False,
    )
    op.create_table(
        "collection_center",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_center_tenant_code"),
    )
    op.create_index(
        op.f("ix_collection_center_branch_id"), "collection_center", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_collection_center_status"), "collection_center", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_collection_center_tenant_id"), "collection_center", ["tenant_id"], unique=False
    )
    op.create_table(
        "collection_center_config",
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_center_config_center_id"),
        "collection_center_config",
        ["center_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_collection_center_config_center_id"), table_name="collection_center_config"
    )
    op.drop_table("collection_center_config")
    op.drop_index(op.f("ix_collection_center_tenant_id"), table_name="collection_center")
    op.drop_index(op.f("ix_collection_center_status"), table_name="collection_center")
    op.drop_index(op.f("ix_collection_center_branch_id"), table_name="collection_center")
    op.drop_table("collection_center")
    op.drop_index(
        op.f("ix_center_operating_window_center_id"), table_name="center_operating_window"
    )
    op.drop_table("center_operating_window")
    op.drop_index(op.f("ix_center_calendar_entry_center_id"), table_name="center_calendar_entry")
    op.drop_table("center_calendar_entry")
    # ### end Alembic commands ###
