"""notification engine

Revision ID: 5d394226efec
Revises: aa742d7b6987
Create Date: 2026-08-04 23:03:45.801445
"""

import sqlalchemy as sa
from alembic import op

revision = "5d394226efec"
down_revision = "aa742d7b6987"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_name", sa.String(length=120), nullable=False),
        sa.Column("template_key", sa.String(length=60), nullable=False),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("recipient_ref", sa.Uuid(), nullable=True),
        sa.Column("recipient", sa.String(length=200), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("rendered_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("provider_reference", sa.String(length=120), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "template_key", "channel", name="uq_notification_event"),
    )
    op.create_index(op.f("ix_notification_channel"), "notification", ["channel"], unique=False)
    op.create_index(op.f("ix_notification_event_id"), "notification", ["event_id"], unique=False)
    op.create_index(
        "ix_notification_history", "notification", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_notification_recipient_ref"), "notification", ["recipient_ref"], unique=False
    )
    op.create_index(
        "ix_notification_retry", "notification", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(op.f("ix_notification_status"), "notification", ["status"], unique=False)
    op.create_index(
        op.f("ix_notification_template_key"), "notification", ["template_key"], unique=False
    )
    op.create_index(op.f("ix_notification_tenant_id"), "notification", ["tenant_id"], unique=False)
    op.create_table(
        "notification_recipient",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "subject_id", name="uq_notification_recipient"),
    )
    op.create_index(
        op.f("ix_notification_recipient_subject_id"),
        "notification_recipient",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_recipient_tenant_id"),
        "notification_recipient",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_recipient_tenant_id"), table_name="notification_recipient")
    op.drop_index(op.f("ix_notification_recipient_subject_id"), table_name="notification_recipient")
    op.drop_table("notification_recipient")
    op.drop_index(op.f("ix_notification_tenant_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_template_key"), table_name="notification")
    op.drop_index(op.f("ix_notification_status"), table_name="notification")
    op.drop_index("ix_notification_retry", table_name="notification")
    op.drop_index(op.f("ix_notification_recipient_ref"), table_name="notification")
    op.drop_index("ix_notification_history", table_name="notification")
    op.drop_index(op.f("ix_notification_event_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_channel"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
