"""backup run history

Revision ID: 6560a9a90ab9
Revises: a1c7f3b90e22
Create Date: 2026-08-06 01:05:53.726519
"""

import sqlalchemy as sa
from alembic import op

revision = "6560a9a90ab9"
down_revision = "a1c7f3b90e22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backup_run",
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("backup_id", sa.Uuid(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column("tables", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("bytes_written", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("integrity", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backup_run_kind"), "backup_run", ["kind"], unique=False)
    op.create_index(op.f("ix_backup_run_status"), "backup_run", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backup_run_status"), table_name="backup_run")
    op.drop_index(op.f("ix_backup_run_kind"), table_name="backup_run")
    op.drop_table("backup_run")
    # ### end Alembic commands ###
