"""initial platform schema

Revision ID: 6a09fed0151a
Revises:
Create Date: 2026-08-02 05:44:54.917327
"""

import sqlalchemy as sa
from alembic import op

revision = "6a09fed0151a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_record",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_record_action"), "audit_record", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_record_created_at"), "audit_record", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_record_tenant_id"), "audit_record", ["tenant_id"], unique=False)
    op.create_table(
        "config_entry",
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "tenant_id", "key", name="uq_config_scope_tenant_key"),
    )
    op.create_index(op.f("ix_config_entry_key"), "config_entry", ["key"], unique=False)
    op.create_index(op.f("ix_config_entry_tenant_id"), "config_entry", ["tenant_id"], unique=False)
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("org_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("default_locale", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    op.create_table(
        "role",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_role_tenant_name"),
    )
    op.create_index(op.f("ix_role_tenant_id"), "role", ["tenant_id"], unique=False)
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_key", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_key", name="uq_role_permission"),
    )
    op.create_index(
        op.f("ix_role_permission_role_id"), "role_permission", ["role_id"], unique=False
    )
    op.create_table(
        "user_account",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_user_tenant_email"),
    )
    op.create_index(op.f("ix_user_account_email"), "user_account", ["email"], unique=False)
    op.create_index(op.f("ix_user_account_tenant_id"), "user_account", ["tenant_id"], unique=False)
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", "tenant_id", name="uq_user_role_tenant"),
    )
    op.create_index(op.f("ix_user_role_role_id"), "user_role", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_role_tenant_id"), "user_role", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_user_role_user_id"), "user_role", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role_user_id"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_tenant_id"), table_name="user_role")
    op.drop_index(op.f("ix_user_role_role_id"), table_name="user_role")
    op.drop_table("user_role")
    op.drop_index(op.f("ix_user_account_tenant_id"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_role_permission_role_id"), table_name="role_permission")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_role_tenant_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_config_entry_tenant_id"), table_name="config_entry")
    op.drop_index(op.f("ix_config_entry_key"), table_name="config_entry")
    op.drop_table("config_entry")
    op.drop_index(op.f("ix_audit_record_tenant_id"), table_name="audit_record")
    op.drop_index(op.f("ix_audit_record_created_at"), table_name="audit_record")
    op.drop_index(op.f("ix_audit_record_action"), table_name="audit_record")
    op.drop_table("audit_record")
    # ### end Alembic commands ###
