"""receipt engine

Revision ID: 76b51e9e9990
Revises: 96442d50d1f5
Create Date: 2026-08-05 01:19:33.807733
"""

import sqlalchemy as sa
from alembic import op

revision = "76b51e9e9990"
down_revision = "96442d50d1f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipt",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_number", sa.String(length=30), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("supplier_code", sa.String(length=30), nullable=False),
        sa.Column("payment_number", sa.String(length=30), nullable=False),
        sa.Column("payment_reference", sa.String(length=120), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("adjustments_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("render_format", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "payment_id", name="uq_receipt_payment"),
        sa.UniqueConstraint("tenant_id", "receipt_number", name="uq_receipt_number"),
    )
    op.create_index("ix_receipt_history", "receipt", ["tenant_id", "generated_at"], unique=False)
    op.create_index(op.f("ix_receipt_payment_id"), "receipt", ["payment_id"], unique=False)
    op.create_index(op.f("ix_receipt_status"), "receipt", ["status"], unique=False)
    op.create_index(
        "ix_receipt_supplier", "receipt", ["tenant_id", "supplier_id", "status"], unique=False
    )
    op.create_index(op.f("ix_receipt_supplier_id"), "receipt", ["supplier_id"], unique=False)
    op.create_index(op.f("ix_receipt_tenant_id"), "receipt", ["tenant_id"], unique=False)
    op.create_table(
        "receipt_line",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("settlement_id", sa.Uuid(), nullable=False),
        sa.Column("settlement_number", sa.String(length=30), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=True),
        sa.Column("period_from", sa.Date(), nullable=True),
        sa.Column("period_to", sa.Date(), nullable=True),
        sa.Column("gross_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("adjustments_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_id", "settlement_id", name="uq_receipt_line_settlement"),
    )
    op.create_index(
        op.f("ix_receipt_line_receipt_id"), "receipt_line", ["receipt_id"], unique=False
    )
    op.create_index(
        op.f("ix_receipt_line_settlement_id"), "receipt_line", ["settlement_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_line_settlement_id"), table_name="receipt_line")
    op.drop_index(op.f("ix_receipt_line_receipt_id"), table_name="receipt_line")
    op.drop_table("receipt_line")
    op.drop_index(op.f("ix_receipt_tenant_id"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_supplier_id"), table_name="receipt")
    op.drop_index("ix_receipt_supplier", table_name="receipt")
    op.drop_index(op.f("ix_receipt_status"), table_name="receipt")
    op.drop_index(op.f("ix_receipt_payment_id"), table_name="receipt")
    op.drop_index("ix_receipt_history", table_name="receipt")
    op.drop_table("receipt")
    # ### end Alembic commands ###
