"""operational readiness devices and operators

Revision ID: 7c0f28fe423b
Revises: 5a89536bb4e7
Create Date: 2026-08-03 00:25:28.502166
"""

import sqlalchemy as sa
from alembic import op

revision = "7c0f28fe423b"
down_revision = "5a89536bb4e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("serial_number", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "serial_number", name="uq_device_serial"),
    )
    op.create_index(op.f("ix_device_category"), "device", ["category"], unique=False)
    op.create_index(op.f("ix_device_center_id"), "device", ["center_id"], unique=False)
    op.create_index(op.f("ix_device_status"), "device", ["status"], unique=False)
    op.create_index(op.f("ix_device_tenant_id"), "device", ["tenant_id"], unique=False)
    op.create_table(
        "device_health_report",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("reported_by", sa.Uuid(), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_health_report_device_id"),
        "device_health_report",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_health_report_reported_at"),
        "device_health_report",
        ["reported_at"],
        unique=False,
    )
    op.create_table(
        "operator_assignment",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_label", sa.String(length=20), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("center_id", "user_id", name="uq_operator_center_user"),
    )
    op.create_index(
        op.f("ix_operator_assignment_center_id"), "operator_assignment", ["center_id"], unique=False
    )
    op.create_index(
        op.f("ix_operator_assignment_tenant_id"), "operator_assignment", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_operator_assignment_user_id"), "operator_assignment", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operator_assignment_user_id"), table_name="operator_assignment")
    op.drop_index(op.f("ix_operator_assignment_tenant_id"), table_name="operator_assignment")
    op.drop_index(op.f("ix_operator_assignment_center_id"), table_name="operator_assignment")
    op.drop_table("operator_assignment")
    op.drop_index(op.f("ix_device_health_report_reported_at"), table_name="device_health_report")
    op.drop_index(op.f("ix_device_health_report_device_id"), table_name="device_health_report")
    op.drop_table("device_health_report")
    op.drop_index(op.f("ix_device_tenant_id"), table_name="device")
    op.drop_index(op.f("ix_device_status"), table_name="device")
    op.drop_index(op.f("ix_device_center_id"), table_name="device")
    op.drop_index(op.f("ix_device_category"), table_name="device")
    op.drop_table("device")
    # ### end Alembic commands ###
