"""settlement foundation

Revision ID: 86e2cdb89091
Revises: a4d8a3b2a10f
Create Date: 2026-08-04 00:16:57.170026
"""

import sqlalchemy as sa
from alembic import op

revision = "86e2cdb89091"
down_revision = "a4d8a3b2a10f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settlement",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("settlement_number", sa.String(length=30), nullable=False),
        sa.Column("period_from", sa.Date(), nullable=False),
        sa.Column("period_to", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("adjustments_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "settlement_number", name="uq_settlement_number"),
    )
    op.create_index(op.f("ix_settlement_center_id"), "settlement", ["center_id"], unique=False)
    op.create_index(op.f("ix_settlement_status"), "settlement", ["status"], unique=False)
    op.create_index(op.f("ix_settlement_supplier_id"), "settlement", ["supplier_id"], unique=False)
    op.create_index(
        "ix_settlement_supplier_period",
        "settlement",
        ["tenant_id", "supplier_id", "period_from"],
        unique=False,
    )
    op.create_index(op.f("ix_settlement_tenant_id"), "settlement", ["tenant_id"], unique=False)
    op.create_table(
        "settlement_line",
        sa.Column("settlement_id", sa.Uuid(), nullable=False),
        sa.Column("calculation_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("quantity_unit", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("trace_reference", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("settlement_id", "calculation_id", name="uq_settlement_line_calc"),
        sa.UniqueConstraint("settlement_id", "transaction_id", name="uq_settlement_line_tx"),
    )
    op.create_index(
        op.f("ix_settlement_line_calculation_id"),
        "settlement_line",
        ["calculation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_settlement_line_settlement_id"), "settlement_line", ["settlement_id"], unique=False
    )
    op.create_index(
        op.f("ix_settlement_line_transaction_id"),
        "settlement_line",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settlement_line_transaction_id"), table_name="settlement_line")
    op.drop_index(op.f("ix_settlement_line_settlement_id"), table_name="settlement_line")
    op.drop_index(op.f("ix_settlement_line_calculation_id"), table_name="settlement_line")
    op.drop_table("settlement_line")
    op.drop_index(op.f("ix_settlement_tenant_id"), table_name="settlement")
    op.drop_index("ix_settlement_supplier_period", table_name="settlement")
    op.drop_index(op.f("ix_settlement_supplier_id"), table_name="settlement")
    op.drop_index(op.f("ix_settlement_status"), table_name="settlement")
    op.drop_index(op.f("ix_settlement_center_id"), table_name="settlement")
    op.drop_table("settlement")
    # ### end Alembic commands ###
