"""payment execution engine

Revision ID: 96442d50d1f5
Revises: 5d394226efec
Create Date: 2026-08-05 00:33:12.107570
"""

import sqlalchemy as sa
from alembic import op

revision = "96442d50d1f5"
down_revision = "5d394226efec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("payment_number", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("method_details", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_payment_idempotency"),
        sa.UniqueConstraint("tenant_id", "payment_number", name="uq_payment_number"),
    )
    op.create_index("ix_payment_history", "payment", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_payment_status"), "payment", ["status"], unique=False)
    op.create_index(
        "ix_payment_supplier", "payment", ["tenant_id", "supplier_id", "status"], unique=False
    )
    op.create_index(op.f("ix_payment_supplier_id"), "payment", ["supplier_id"], unique=False)
    op.create_index(op.f("ix_payment_tenant_id"), "payment", ["tenant_id"], unique=False)
    op.create_table(
        "payment_attempt",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", "attempt_number", name="uq_payment_attempt_number"),
    )
    op.create_index(
        op.f("ix_payment_attempt_payment_id"), "payment_attempt", ["payment_id"], unique=False
    )
    op.create_table(
        "payment_line",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("settlement_id", sa.Uuid(), nullable=False),
        sa.Column("settlement_number", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id", "settlement_id", name="uq_payment_line_settlement"),
    )
    op.create_index(
        op.f("ix_payment_line_payment_id"), "payment_line", ["payment_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_line_settlement_id"), "payment_line", ["settlement_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_line_settlement_id"), table_name="payment_line")
    op.drop_index(op.f("ix_payment_line_payment_id"), table_name="payment_line")
    op.drop_table("payment_line")
    op.drop_index(op.f("ix_payment_attempt_payment_id"), table_name="payment_attempt")
    op.drop_table("payment_attempt")
    op.drop_index(op.f("ix_payment_tenant_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_supplier_id"), table_name="payment")
    op.drop_index("ix_payment_supplier", table_name="payment")
    op.drop_index(op.f("ix_payment_status"), table_name="payment")
    op.drop_index("ix_payment_history", table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
