"""pricing matrix foundation

Revision ID: a4d8a3b2a10f
Revises: bd54cc2d0709
Create Date: 2026-08-03 22:14:25.727387
"""

import sqlalchemy as sa
from alembic import op

revision = "a4d8a3b2a10f"
down_revision = "bd54cc2d0709"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_matrix",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("rate_card_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("product_code", sa.String(length=40), nullable=False),
        sa.Column("product_name", sa.String(length=120), nullable=False),
        sa.Column("dimension_code", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rate_card_id",
            "product_code",
            "dimension_code",
            name="uq_matrix_card_product_dimension",
        ),
    )
    op.create_index(
        op.f("ix_pricing_matrix_product_code"), "pricing_matrix", ["product_code"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_matrix_rate_card_id"), "pricing_matrix", ["rate_card_id"], unique=False
    )
    op.create_index(op.f("ix_pricing_matrix_status"), "pricing_matrix", ["status"], unique=False)
    op.create_index(
        op.f("ix_pricing_matrix_tenant_id"), "pricing_matrix", ["tenant_id"], unique=False
    )
    op.create_table(
        "pricing_matrix_row",
        sa.Column("matrix_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("from_value", sa.Float(), nullable=False),
        sa.Column("to_value", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("to_value > from_value", name="ck_matrix_row_range"),
        sa.CheckConstraint("unit_price > 0", name="ck_matrix_row_price"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_matrix_row_lookup",
        "pricing_matrix_row",
        ["matrix_id", "active", "from_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_matrix_row_matrix_id"), "pricing_matrix_row", ["matrix_id"], unique=False
    )
    op.create_table(
        "quality_dimension",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_quality_dimension_tenant_code"),
    )
    op.create_index(
        op.f("ix_quality_dimension_tenant_id"), "quality_dimension", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quality_dimension_tenant_id"), table_name="quality_dimension")
    op.drop_table("quality_dimension")
    op.drop_index(op.f("ix_pricing_matrix_row_matrix_id"), table_name="pricing_matrix_row")
    op.drop_index("ix_matrix_row_lookup", table_name="pricing_matrix_row")
    op.drop_table("pricing_matrix_row")
    op.drop_index(op.f("ix_pricing_matrix_tenant_id"), table_name="pricing_matrix")
    op.drop_index(op.f("ix_pricing_matrix_status"), table_name="pricing_matrix")
    op.drop_index(op.f("ix_pricing_matrix_rate_card_id"), table_name="pricing_matrix")
    op.drop_index(op.f("ix_pricing_matrix_product_code"), table_name="pricing_matrix")
    op.drop_table("pricing_matrix")
    # ### end Alembic commands ###
