"""projection lifecycle state

Revision ID: aa742d7b6987
Revises: d34a2e05d4e3
Create Date: 2026-08-04 22:19:28.998909
"""

import sqlalchemy as sa
from alembic import op

revision = "aa742d7b6987"
down_revision = "d34a2e05d4e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projection_state",
        sa.Column("projection_name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_rebuild_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_rebuild_ms", sa.Float(), nullable=True),
        sa.Column("rebuild_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rebuild_total", sa.Integer(), nullable=False),
        sa.Column("rebuild_done", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projection_state_projection_name"),
        "projection_state",
        ["projection_name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projection_state_projection_name"), table_name="projection_state")
    op.drop_table("projection_state")
    # ### end Alembic commands ###
