"""supplier platform

Revision ID: ad283b1e49b5
Revises: 7c0f28fe423b
Create Date: 2026-08-03 00:38:03.597237
"""

import sqlalchemy as sa
from alembic import op

revision = "ad283b1e49b5"
down_revision = "7c0f28fe423b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_supplier_tenant_code"),
    )
    op.create_index(op.f("ix_supplier_branch_id"), "supplier", ["branch_id"], unique=False)
    op.create_index(op.f("ix_supplier_code"), "supplier", ["code"], unique=False)
    op.create_index(op.f("ix_supplier_status"), "supplier", ["status"], unique=False)
    op.create_index(op.f("ix_supplier_tenant_id"), "supplier", ["tenant_id"], unique=False)
    op.create_table(
        "supplier_bank_account",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("account_name", sa.String(length=200), nullable=False),
        sa.Column("account_number", sa.String(length=60), nullable=False),
        sa.Column("bank_code", sa.String(length=40), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_bank_account_supplier_id"),
        "supplier_bank_account",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "supplier_center_assignment",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_id", "center_id", name="uq_supplier_center"),
    )
    op.create_index(
        op.f("ix_supplier_center_assignment_center_id"),
        "supplier_center_assignment",
        ["center_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_center_assignment_supplier_id"),
        "supplier_center_assignment",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_center_assignment_tenant_id"),
        "supplier_center_assignment",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "supplier_document",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("file_name", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("object_key", sa.String(length=300), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_document_supplier_id"), "supplier_document", ["supplier_id"], unique=False
    )
    op.create_table(
        "supplier_profile",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("national_id", sa.String(length=60), nullable=False),
        sa.Column("village", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_profile_full_name"), "supplier_profile", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_supplier_profile_phone"), "supplier_profile", ["phone"], unique=False)
    op.create_index(
        op.f("ix_supplier_profile_supplier_id"), "supplier_profile", ["supplier_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_profile_supplier_id"), table_name="supplier_profile")
    op.drop_index(op.f("ix_supplier_profile_phone"), table_name="supplier_profile")
    op.drop_index(op.f("ix_supplier_profile_full_name"), table_name="supplier_profile")
    op.drop_table("supplier_profile")
    op.drop_index(op.f("ix_supplier_document_supplier_id"), table_name="supplier_document")
    op.drop_table("supplier_document")
    op.drop_index(
        op.f("ix_supplier_center_assignment_tenant_id"), table_name="supplier_center_assignment"
    )
    op.drop_index(
        op.f("ix_supplier_center_assignment_supplier_id"), table_name="supplier_center_assignment"
    )
    op.drop_index(
        op.f("ix_supplier_center_assignment_center_id"), table_name="supplier_center_assignment"
    )
    op.drop_table("supplier_center_assignment")
    op.drop_index(op.f("ix_supplier_bank_account_supplier_id"), table_name="supplier_bank_account")
    op.drop_table("supplier_bank_account")
    op.drop_index(op.f("ix_supplier_tenant_id"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_status"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_code"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_branch_id"), table_name="supplier")
    op.drop_table("supplier")
    # ### end Alembic commands ###
