"""DEMO-009 sales: customers, deliveries and billing

The receivable side of the business, in eight new tables:

  customer, delivery_plan          — who we sell to, and at what agreed rate
  milk_delivery                    — milk leaving for a customer, priced and stored
  customer_invoice, ..._line       — the monthly statement, built from deliveries
  customer_payment, ..._allocation — money received, and which invoices it settled
  customer_receipt                 — proof, generated from the payment event

Purely additive: no existing table is touched, no row is rewritten, and nothing
about procurement changes. Every table carries `tenant_id`, so the RLS policy
builder picks them up automatically (`tenant_tables()` is derived from the
metadata rather than hand-kept, which is what SEC-002 established).

The unique constraints are the load-bearing part:

  * one delivery per customer, day and slot — a second morning delivery is a
    correction, not another sale, and would otherwise double the bill;
  * one invoice per customer and period, and one invoice line per delivery, so
    the same milk cannot be billed twice;
  * one receipt per payment, because a second would be a second proof of the
    same money.

Reversible: the downgrade drops the eight tables. Nothing outside them refers
to them.
"""

import sqlalchemy as sa
from alembic import op

revision = "b3e18f736894"
down_revision = "b7c2e94d1a55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("customer_type", sa.String(length=20), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("alternate_phone", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("billing_mode", sa.String(length=16), nullable=False),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_customer_tenant_code"),
    )
    op.create_index(op.f("ix_customer_code"), "customer", ["code"], unique=False)
    op.create_index(op.f("ix_customer_status"), "customer", ["status"], unique=False)
    op.create_index(op.f("ix_customer_tenant_id"), "customer", ["tenant_id"], unique=False)
    op.create_table(
        "customer_invoice",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=32), nullable=False),
        sa.Column("period_from", sa.Date(), nullable=False),
        sa.Column("period_to", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("adjustments", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("previous_balance", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("amount_due", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "invoice_number", name="uq_invoice_tenant_number"),
    )
    op.create_index(
        op.f("ix_customer_invoice_customer_id"), "customer_invoice", ["customer_id"], unique=False
    )
    # PARTIAL, excluding cancelled — see the model's comment. A plain unique
    # constraint would let a cancelled invoice block its own period forever.
    op.create_index(
        "uq_invoice_customer_period",
        "customer_invoice",
        ["tenant_id", "customer_id", "period_from", "period_to"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelled'"),
        sqlite_where=sa.text("status <> 'cancelled'"),
    )
    op.create_index(
        op.f("ix_customer_invoice_invoice_number"),
        "customer_invoice",
        ["invoice_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_invoice_status"), "customer_invoice", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_customer_invoice_tenant_id"), "customer_invoice", ["tenant_id"], unique=False
    )
    op.create_table(
        "customer_invoice_line",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("slot", sa.String(length=10), nullable=False),
        sa.Column("product", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("quantity_unit", sa.String(length=8), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "delivery_id", name="uq_invoice_line_delivery"),
    )
    op.create_index(
        op.f("ix_customer_invoice_line_delivery_id"),
        "customer_invoice_line",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_invoice_line_invoice_id"),
        "customer_invoice_line",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_invoice_line_tenant_id"),
        "customer_invoice_line",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "customer_payment",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("payment_number", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("reference", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.String(length=300), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "payment_number", name="uq_customer_payment_number"),
    )
    op.create_index(
        op.f("ix_customer_payment_customer_id"), "customer_payment", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_payment_payment_number"),
        "customer_payment",
        ["payment_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_payment_status"), "customer_payment", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_customer_payment_tenant_id"), "customer_payment", ["tenant_id"], unique=False
    )
    op.create_table(
        "customer_payment_allocation",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_payment_allocation_invoice_id"),
        "customer_payment_allocation",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_payment_allocation_payment_id"),
        "customer_payment_allocation",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_payment_allocation_tenant_id"),
        "customer_payment_allocation",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "customer_receipt",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_number", sa.String(length=32), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("payment_number", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("customer_code", sa.String(length=24), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("reference", sa.String(length=80), nullable=False),
        sa.Column("applied_to", sa.String(length=300), nullable=False),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "payment_id", name="uq_customer_receipt_payment"),
        sa.UniqueConstraint("tenant_id", "receipt_number", name="uq_customer_receipt_number"),
    )
    op.create_index(
        op.f("ix_customer_receipt_customer_id"), "customer_receipt", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_receipt_payment_id"), "customer_receipt", ["payment_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_receipt_receipt_number"),
        "customer_receipt",
        ["receipt_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_receipt_tenant_id"), "customer_receipt", ["tenant_id"], unique=False
    )
    op.create_table(
        "delivery_plan",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("product", sa.String(length=40), nullable=False),
        sa.Column("default_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("quantity_unit", sa.String(length=8), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delivery_plan_active"), "delivery_plan", ["active"], unique=False)
    op.create_index(
        op.f("ix_delivery_plan_customer_id"), "delivery_plan", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_plan_tenant_id"), "delivery_plan", ["tenant_id"], unique=False
    )
    op.create_table(
        "milk_delivery",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("slot", sa.String(length=10), nullable=False),
        sa.Column("product", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("quantity_unit", sa.String(length=8), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.String(length=300), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "customer_id",
            "delivery_date",
            "slot",
            name="uq_delivery_customer_date_slot",
        ),
    )
    op.create_index(
        op.f("ix_milk_delivery_customer_id"), "milk_delivery", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_milk_delivery_delivery_date"), "milk_delivery", ["delivery_date"], unique=False
    )
    op.create_index(
        op.f("ix_milk_delivery_invoice_id"), "milk_delivery", ["invoice_id"], unique=False
    )
    op.create_index(op.f("ix_milk_delivery_status"), "milk_delivery", ["status"], unique=False)
    op.create_index(
        op.f("ix_milk_delivery_tenant_id"), "milk_delivery", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_milk_delivery_tenant_id"), table_name="milk_delivery")
    op.drop_index(op.f("ix_milk_delivery_status"), table_name="milk_delivery")
    op.drop_index(op.f("ix_milk_delivery_invoice_id"), table_name="milk_delivery")
    op.drop_index(op.f("ix_milk_delivery_delivery_date"), table_name="milk_delivery")
    op.drop_index(op.f("ix_milk_delivery_customer_id"), table_name="milk_delivery")
    op.drop_table("milk_delivery")
    op.drop_index(op.f("ix_delivery_plan_tenant_id"), table_name="delivery_plan")
    op.drop_index(op.f("ix_delivery_plan_customer_id"), table_name="delivery_plan")
    op.drop_index(op.f("ix_delivery_plan_active"), table_name="delivery_plan")
    op.drop_table("delivery_plan")
    op.drop_index(op.f("ix_customer_receipt_tenant_id"), table_name="customer_receipt")
    op.drop_index(op.f("ix_customer_receipt_receipt_number"), table_name="customer_receipt")
    op.drop_index(op.f("ix_customer_receipt_payment_id"), table_name="customer_receipt")
    op.drop_index(op.f("ix_customer_receipt_customer_id"), table_name="customer_receipt")
    op.drop_table("customer_receipt")
    op.drop_index(
        op.f("ix_customer_payment_allocation_tenant_id"), table_name="customer_payment_allocation"
    )
    op.drop_index(
        op.f("ix_customer_payment_allocation_payment_id"), table_name="customer_payment_allocation"
    )
    op.drop_index(
        op.f("ix_customer_payment_allocation_invoice_id"), table_name="customer_payment_allocation"
    )
    op.drop_table("customer_payment_allocation")
    op.drop_index(op.f("ix_customer_payment_tenant_id"), table_name="customer_payment")
    op.drop_index(op.f("ix_customer_payment_status"), table_name="customer_payment")
    op.drop_index(op.f("ix_customer_payment_payment_number"), table_name="customer_payment")
    op.drop_index(op.f("ix_customer_payment_customer_id"), table_name="customer_payment")
    op.drop_table("customer_payment")
    op.drop_index(op.f("ix_customer_invoice_line_tenant_id"), table_name="customer_invoice_line")
    op.drop_index(op.f("ix_customer_invoice_line_invoice_id"), table_name="customer_invoice_line")
    op.drop_index(op.f("ix_customer_invoice_line_delivery_id"), table_name="customer_invoice_line")
    op.drop_table("customer_invoice_line")
    op.drop_index(op.f("ix_customer_invoice_tenant_id"), table_name="customer_invoice")
    op.drop_index(op.f("ix_customer_invoice_status"), table_name="customer_invoice")
    op.drop_index(op.f("ix_customer_invoice_invoice_number"), table_name="customer_invoice")
    op.drop_index(op.f("ix_customer_invoice_customer_id"), table_name="customer_invoice")
    op.drop_table("customer_invoice")
    op.drop_index(op.f("ix_customer_tenant_id"), table_name="customer")
    op.drop_index(op.f("ix_customer_status"), table_name="customer")
    op.drop_index(op.f("ix_customer_code"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
