"""rate card foundation

Revision ID: bd54cc2d0709
Revises: cb7d9d9d4e46
Create Date: 2026-08-03 02:20:23.984310
"""

import sqlalchemy as sa
from alembic import op

revision = "bd54cc2d0709"
down_revision = "cb7d9d9d4e46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_card",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_until", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "code", "version", name="uq_rate_card_tenant_code_version"
        ),
    )
    op.create_index(
        "ix_rate_card_active_window",
        "rate_card",
        ["tenant_id", "status", "effective_from"],
        unique=False,
    )
    op.create_index(op.f("ix_rate_card_branch_id"), "rate_card", ["branch_id"], unique=False)
    op.create_index(op.f("ix_rate_card_code"), "rate_card", ["code"], unique=False)
    op.create_index(op.f("ix_rate_card_status"), "rate_card", ["status"], unique=False)
    op.create_index(op.f("ix_rate_card_tenant_id"), "rate_card", ["tenant_id"], unique=False)
    op.create_table(
        "rate_card_center_assignment",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("rate_card_id", sa.Uuid(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rate_card_id", "center_id", name="uq_rate_card_center"),
    )
    op.create_index(
        op.f("ix_rate_card_center_assignment_center_id"),
        "rate_card_center_assignment",
        ["center_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_card_center_assignment_rate_card_id"),
        "rate_card_center_assignment",
        ["rate_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_card_center_assignment_tenant_id"),
        "rate_card_center_assignment",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "rate_card_product_assignment",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("rate_card_id", sa.Uuid(), nullable=False),
        sa.Column("product_code", sa.String(length=40), nullable=False),
        sa.Column("product_name", sa.String(length=120), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rate_card_id", "product_code", name="uq_rate_card_product"),
    )
    op.create_index(
        op.f("ix_rate_card_product_assignment_product_code"),
        "rate_card_product_assignment",
        ["product_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_card_product_assignment_rate_card_id"),
        "rate_card_product_assignment",
        ["rate_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_card_product_assignment_tenant_id"),
        "rate_card_product_assignment",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rate_card_product_assignment_tenant_id"), table_name="rate_card_product_assignment"
    )
    op.drop_index(
        op.f("ix_rate_card_product_assignment_rate_card_id"),
        table_name="rate_card_product_assignment",
    )
    op.drop_index(
        op.f("ix_rate_card_product_assignment_product_code"),
        table_name="rate_card_product_assignment",
    )
    op.drop_table("rate_card_product_assignment")
    op.drop_index(
        op.f("ix_rate_card_center_assignment_tenant_id"), table_name="rate_card_center_assignment"
    )
    op.drop_index(
        op.f("ix_rate_card_center_assignment_rate_card_id"),
        table_name="rate_card_center_assignment",
    )
    op.drop_index(
        op.f("ix_rate_card_center_assignment_center_id"), table_name="rate_card_center_assignment"
    )
    op.drop_table("rate_card_center_assignment")
    op.drop_index(op.f("ix_rate_card_tenant_id"), table_name="rate_card")
    op.drop_index(op.f("ix_rate_card_status"), table_name="rate_card")
    op.drop_index(op.f("ix_rate_card_code"), table_name="rate_card")
    op.drop_index(op.f("ix_rate_card_branch_id"), table_name="rate_card")
    op.drop_index("ix_rate_card_active_window", table_name="rate_card")
    op.drop_table("rate_card")
    # ### end Alembic commands ###
