"""event relay outbox

Revision ID: cb7d9d9d4e46
Revises: 15471450e001
Create Date: 2026-08-03 01:28:59.311956
"""

import sqlalchemy as sa
from alembic import op

revision = "cb7d9d9d4e46"
down_revision = "15471450e001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letter_queue",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("event_name", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("dead_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("replayed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replay_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dead_letter_queue_event_id"), "dead_letter_queue", ["event_id"], unique=True
    )
    op.create_index(
        op.f("ix_dead_letter_queue_tenant_id"), "dead_letter_queue", ["tenant_id"], unique=False
    )
    op.create_table(
        "event_delivery",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("transport", sa.String(length=30), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_delivery_event_id"), "event_delivery", ["event_id"], unique=False
    )
    op.create_table(
        "event_outbox",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("aggregate_type", sa.String(length=60), nullable=True),
        sa.Column("aggregate_id", sa.Uuid(), nullable=True),
        sa.Column("event_name", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_outbox_aggregate_id"), "event_outbox", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_outbox_correlation_id"), "event_outbox", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_outbox_event_name"), "event_outbox", ["event_name"], unique=False
    )
    op.create_index(op.f("ix_event_outbox_status"), "event_outbox", ["status"], unique=False)
    op.create_index(op.f("ix_event_outbox_tenant_id"), "event_outbox", ["tenant_id"], unique=False)
    op.create_index(
        "ix_outbox_dispatch", "event_outbox", ["status", "next_attempt_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_dispatch", table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_tenant_id"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_status"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_event_name"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_correlation_id"), table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_aggregate_id"), table_name="event_outbox")
    op.drop_table("event_outbox")
    op.drop_index(op.f("ix_event_delivery_event_id"), table_name="event_delivery")
    op.drop_table("event_delivery")
    op.drop_index(op.f("ix_dead_letter_queue_tenant_id"), table_name="dead_letter_queue")
    op.drop_index(op.f("ix_dead_letter_queue_event_id"), table_name="dead_letter_queue")
    op.drop_table("dead_letter_queue")
    # ### end Alembic commands ###
