"""payables index and money constraint (ARCH-001)

Two findings from the final production review.

**The index.** The payables selector — the screen an operator opens to pay
people — filters `(tenant_id, status='finalized')`. The only usable index
started `(tenant_id, supplier_id, period_from)`, so PostgreSQL read every
settlement the tenant had ever had to find the handful that were unpaid.
Five years of history is ~50,000 rows scanned to locate ~200.

**The constraint.** The service refuses a non-positive payment; the database
did not. The platform has two check constraints in fifty-seven tables, and
this is the column whose corruption costs money. A constraint costs nothing
to evaluate and closes every path the service layer does not sit in front of.

Original autogenerate header

Revision ID: ced805436869
Revises: f73f41473469
Create Date: 2026-08-07 16:39:42.749521
"""

from alembic import op

revision = "ced805436869"
down_revision = "f73f41473469"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_settlement_payable", "settlement", ["tenant_id", "status"], unique=False)
    # ### end Alembic commands ###

    with op.batch_alter_table("payment") as batch:
        batch.create_check_constraint("ck_payment_amount_positive", "amount > 0")


def downgrade() -> None:
    with op.batch_alter_table("payment") as batch:
        batch.drop_constraint("ck_payment_amount_positive", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settlement_payable", table_name="settlement")
    # ### end Alembic commands ###
