"""consumer framework and projections

Revision ID: d34a2e05d4e3
Revises: 47434355bf8f
Create Date: 2026-08-04 02:23:30.890762
"""

import sqlalchemy as sa
from alembic import op

revision = "d34a2e05d4e3"
down_revision = "47434355bf8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumer_cursor",
        sa.Column("consumer_name", sa.String(length=80), nullable=False),
        sa.Column("position_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position_event_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumer_cursor_consumer_name"), "consumer_cursor", ["consumer_name"], unique=True
    )
    op.create_table(
        "consumer_execution",
        sa.Column("consumer_name", sa.String(length=80), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_name", sa.String(length=120), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consumer_name", "event_id", name="uq_consumer_execution"),
    )
    op.create_index(
        op.f("ix_consumer_execution_consumer_name"),
        "consumer_execution",
        ["consumer_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_execution_event_id"), "consumer_execution", ["event_id"], unique=False
    )
    op.create_index(
        "ix_consumer_execution_status",
        "consumer_execution",
        ["consumer_name", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumer_execution_tenant_id"), "consumer_execution", ["tenant_id"], unique=False
    )
    op.create_table(
        "projection_center_totals",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("center_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transactions", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("total_net_weight", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("payable_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "day", "center_id", name="uq_projection_center"),
    )
    op.create_index(
        op.f("ix_projection_center_totals_center_id"),
        "projection_center_totals",
        ["center_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projection_center_totals_day"), "projection_center_totals", ["day"], unique=False
    )
    op.create_index(
        op.f("ix_projection_center_totals_tenant_id"),
        "projection_center_totals",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "projection_daily_totals",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transactions", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("total_net_weight", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("payable_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "day", name="uq_projection_daily"),
    )
    op.create_index(
        op.f("ix_projection_daily_totals_day"), "projection_daily_totals", ["day"], unique=False
    )
    op.create_index(
        op.f("ix_projection_daily_totals_tenant_id"),
        "projection_daily_totals",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "projection_supplier_totals",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transactions", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("total_net_weight", sa.Numeric(precision=16, scale=3), nullable=False),
        sa.Column("payable_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "day", "supplier_id", name="uq_projection_supplier"),
    )
    op.create_index(
        op.f("ix_projection_supplier_totals_day"),
        "projection_supplier_totals",
        ["day"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projection_supplier_totals_supplier_id"),
        "projection_supplier_totals",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projection_supplier_totals_tenant_id"),
        "projection_supplier_totals",
        ["tenant_id"],
        unique=False,
    )
    op.create_index("ix_outbox_consume", "event_outbox", ["created_at", "id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_consume", table_name="event_outbox")
    op.drop_index(
        op.f("ix_projection_supplier_totals_tenant_id"), table_name="projection_supplier_totals"
    )
    op.drop_index(
        op.f("ix_projection_supplier_totals_supplier_id"), table_name="projection_supplier_totals"
    )
    op.drop_index(
        op.f("ix_projection_supplier_totals_day"), table_name="projection_supplier_totals"
    )
    op.drop_table("projection_supplier_totals")
    op.drop_index(
        op.f("ix_projection_daily_totals_tenant_id"), table_name="projection_daily_totals"
    )
    op.drop_index(op.f("ix_projection_daily_totals_day"), table_name="projection_daily_totals")
    op.drop_table("projection_daily_totals")
    op.drop_index(
        op.f("ix_projection_center_totals_tenant_id"), table_name="projection_center_totals"
    )
    op.drop_index(op.f("ix_projection_center_totals_day"), table_name="projection_center_totals")
    op.drop_index(
        op.f("ix_projection_center_totals_center_id"), table_name="projection_center_totals"
    )
    op.drop_table("projection_center_totals")
    op.drop_index(op.f("ix_consumer_execution_tenant_id"), table_name="consumer_execution")
    op.drop_index("ix_consumer_execution_status", table_name="consumer_execution")
    op.drop_index(op.f("ix_consumer_execution_event_id"), table_name="consumer_execution")
    op.drop_index(op.f("ix_consumer_execution_consumer_name"), table_name="consumer_execution")
    op.drop_table("consumer_execution")
    op.drop_index(op.f("ix_consumer_cursor_consumer_name"), table_name="consumer_cursor")
    op.drop_table("consumer_cursor")
    # ### end Alembic commands ###
