"""LACTEVA-PRICING-002 authorized rate override

BR-0029. `unit_price` keeps its meaning — the EFFECTIVE rate a collection is
paid at — so settlement and the parchi need no change and cannot accidentally
consume a rate that was superseded. The resolved rate moves into
`base_unit_price` when an override happens, and is null on every existing row
because none of them was overridden.

Additive and nullable throughout: expand-only, so a rollback to the previous
release keeps serving.

Revision ID: df05e4777398
Revises: c9e4b2a71f05
Create Date: 2026-08-31 20:36:18.422943
"""

import sqlalchemy as sa
from alembic import op

revision = "df05e4777398"
down_revision = "c9e4b2a71f05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "milk_collection_transaction",
        sa.Column("base_unit_price", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "milk_collection_transaction",
        sa.Column("override_reason", sa.String(length=300), nullable=True),
    )
    op.add_column(
        "milk_collection_transaction", sa.Column("overridden_by", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "milk_collection_transaction",
        sa.Column("overridden_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("milk_collection_transaction", "overridden_at")
    op.drop_column("milk_collection_transaction", "overridden_by")
    op.drop_column("milk_collection_transaction", "override_reason")
    op.drop_column("milk_collection_transaction", "base_unit_price")
    # ### end Alembic commands ###
