"""offline collection sync

Revision ID: e8845cde90c0
Revises: 76b51e9e9990
Create Date: 2026-08-05 01:59:47.693737
"""

import sqlalchemy as sa
from alembic import op

revision = "e8845cde90c0"
down_revision = "76b51e9e9990"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_operation",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=80), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("client_reference", sa.String(length=80), nullable=True),
        sa.Column("target_ref", sa.String(length=80), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=True),
        sa.Column("conflict_reason", sa.String(length=40), nullable=True),
        sa.Column("conflict_detail", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "operation_id", name="uq_sync_operation_id"),
    )
    op.create_index(
        "ix_sync_operation_device",
        "sync_operation",
        ["tenant_id", "device_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sync_operation_monitor",
        "sync_operation",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_operation_operation_id"), "sync_operation", ["operation_id"], unique=False
    )
    op.create_index(
        "ix_sync_operation_reference",
        "sync_operation",
        ["tenant_id", "client_reference"],
        unique=False,
    )
    op.create_index(op.f("ix_sync_operation_status"), "sync_operation", ["status"], unique=False)
    op.create_index(
        op.f("ix_sync_operation_tenant_id"), "sync_operation", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_operation_tenant_id"), table_name="sync_operation")
    op.drop_index(op.f("ix_sync_operation_status"), table_name="sync_operation")
    op.drop_index("ix_sync_operation_reference", table_name="sync_operation")
    op.drop_index(op.f("ix_sync_operation_operation_id"), table_name="sync_operation")
    op.drop_index("ix_sync_operation_monitor", table_name="sync_operation")
    op.drop_index("ix_sync_operation_device", table_name="sync_operation")
    op.drop_table("sync_operation")
    # ### end Alembic commands ###
