"""LACTEVA-NOTIFY-003 supplier email

WO-52. Optional and empty for every existing row: a smallholder dairy farmer is
reachable by phone, not by mail. The column exists because some suppliers are
institutions, and because the notification directory has always been able to
carry an address that nothing populated. Additive and nullable — expand-only.

Revision ID: e8edb960dcbe
Revises: df05e4777398
Create Date: 2026-08-31 20:46:18.807642
"""

import sqlalchemy as sa
from alembic import op

revision = "e8edb960dcbe"
down_revision = "df05e4777398"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL with a SERVER default, not merely a Python one.
    #
    # Autogenerate wrote this as a bare `nullable=False` because the model
    # carries `default=""`, which SQLAlchemy applies in the ORM — so the whole
    # unit suite passed on SQLite and the PostgreSQL proof failed on the first
    # insert that does not go through the ORM: `null value in column "email"
    # violates not-null constraint`. A default that only exists in Python is
    # not a default the database has, and adding a NOT NULL column to a
    # populated table needs one the database can apply itself.
    op.add_column(
        "supplier_profile",
        sa.Column("email", sa.String(length=200), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_profile", "email")
    # ### end Alembic commands ###
