"""LACTEVA-NOTIFY-003 supplier email

WO-52. Optional and empty for every existing row: a smallholder dairy farmer is
reachable by phone, not by mail. The column exists because some suppliers are
institutions, and because the notification directory has always been able to
carry an address that nothing populated. Additive and nullable — expand-only.

Revision ID: e8edb960dcbe
Revises: df05e4777398
Create Date: 2026-08-31 20:46:18.807642
"""
from alembic import op
import sqlalchemy as sa


revision = 'e8edb960dcbe'
down_revision = 'df05e4777398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_profile', sa.Column('email', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_profile', 'email')
    # ### end Alembic commands ###
