"""idempotency records (IDM-001)

One HTTP request, remembered long enough to recognise its retry.

The table is tenant-owned, so it gets the standard policy — SEC-002 made an
unprotected tenant table a build failure, and this is the first new table
since. `tenant_id` is nullable because a platform-level principal has no
tenant; the policy treats NULL as globally visible, which is right here
because the UNIQUE pair is `(tenant_id, key)` and a tenantless key cannot
collide with a tenant's.

Original autogenerate header

Revision ID: f73f41473469
Revises: f2d18ba60c47
Create Date: 2026-08-07 00:41:32.229486
"""

import sqlalchemy as sa
from alembic import op

revision = "f73f41473469"
down_revision = "f2d18ba60c47"
branch_labels = None
depends_on = None


#: Tables this migration grants a policy to. Imported by the SEC-002 coverage
#: guard — which is what failed when this table first appeared, exactly as it
#: was built to.
POLICY_TABLES = ("idempotency_record",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_record",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_idempotency_tenant_key"),
    )
    op.create_index("ix_idempotency_expiry", "idempotency_record", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_idempotency_record_tenant_id"), "idempotency_record", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # SEC-002: tenant-owned means a policy, always.
    if op.get_bind().dialect.name == "postgresql":
        predicate = (
            "current_setting('lacteva.bypass_rls', true) = 'on' "
            "OR tenant_id IS NULL "
            "OR tenant_id::text = current_setting('lacteva.tenant_id', true)"
        )
        op.execute("ALTER TABLE idempotency_record ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE idempotency_record FORCE ROW LEVEL SECURITY")
        op.execute(
            "CREATE POLICY idempotency_record_tenant_isolation ON idempotency_record "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "DROP POLICY IF EXISTS idempotency_record_tenant_isolation ON idempotency_record"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_idempotency_record_tenant_id"), table_name="idempotency_record")
    op.drop_index("ix_idempotency_expiry", table_name="idempotency_record")
    op.drop_table("idempotency_record")
    # ### end Alembic commands ###
