"""PROD-001 tenant offboarding tombstone

Revision ID: fe59b02bbc68
Revises: dd68ec06c1c0
Create Date: 2026-08-08 12:41:47.116967
"""

import sqlalchemy as sa
from alembic import op

revision = "fe59b02bbc68"
down_revision = "dd68ec06c1c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization", sa.Column("offboarded_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "offboarded_at")
    # ### end Alembic commands ###
