// GENERATED by tools/brand/generate.py — do not edit by hand.
//
// The Lacteva mark, in Dart (LACTEVA-BRAND-004 geometry, BRAND-003 rendering).
// `tools/brand/check_inline.py` regenerates this file and compares it, so an
// edit here is a build failure rather than a second mark.
import 'dart:ui';

/// The drop's tight bounding box in the 64 grid the geometry is authored in.
const Rect kMarkBounds = Rect.fromLTWH(
  24.2,
  30,
  15.6,
  22.7,
);

/// The drop outline, in grid units scaled by [s].
///
/// This is the shape knocked OUT of the can. It is also what the sign-in
/// reveal lights, which is why it has a function of its own.
Path lactevaDropPath(double s) => Path()
  ..moveTo(32 * s, 30 * s)
  ..cubicTo(36.2 * s, 35.9 * s, 39.8 * s, 40.4 * s, 39.8 * s, 44.9 * s)
  ..cubicTo(39.8 * s, 49.208 * s, 36.308 * s, 52.7 * s, 32 * s, 52.7 * s)
  ..cubicTo(27.692 * s, 52.7 * s, 24.2 * s, 49.208 * s, 24.2 * s, 44.9 * s)
  ..cubicTo(24.2 * s, 40.4 * s, 27.8 * s, 35.9 * s, 32 * s, 30 * s)
  ..close();

/// The can's tight bounding box in the same grid.
const Rect kCanBounds = Rect.fromLTWH(
  16,
  12,
  32,
  45,
);

/// The can body, in grid units scaled by [s] (LACTEVA-BRAND-004).
///
/// Fill this, then fill [lactevaDropPath] in the ground colour, and the drop
/// is a knockout. Filling both into ONE path with an even-odd fill type does
/// the same thing in a single pass where a surface wants that.
Path lactevaCanPath(double s) => Path()
  ..moveTo(22 * s, 12 * s)
  ..cubicTo(28.667 * s, 12 * s, 35.333 * s, 12 * s, 42 * s, 12 * s)
  ..cubicTo(42 * s, 13.333 * s, 42 * s, 14.667 * s, 42 * s, 16 * s)
  ..cubicTo(43.333 * s, 16 * s, 44.667 * s, 16 * s, 46 * s, 16 * s)
  ..cubicTo(46 * s, 18 * s, 46 * s, 20 * s, 46 * s, 22 * s)
  ..cubicTo(44.667 * s, 22 * s, 43.333 * s, 22 * s, 42 * s, 22 * s)
  ..cubicTo(42 * s, 22.667 * s, 42 * s, 23.333 * s, 42 * s, 24 * s)
  ..cubicTo(46 * s, 27 * s, 48 * s, 32 * s, 48 * s, 37 * s)
  ..cubicTo(48 * s, 41.667 * s, 48 * s, 46.333 * s, 48 * s, 51 * s)
  ..cubicTo(48 * s, 54.314 * s, 45.314 * s, 57 * s, 42 * s, 57 * s)
  ..cubicTo(35.333 * s, 57 * s, 28.667 * s, 57 * s, 22 * s, 57 * s)
  ..cubicTo(18.686 * s, 57 * s, 16 * s, 54.314 * s, 16 * s, 51 * s)
  ..cubicTo(16 * s, 46.333 * s, 16 * s, 41.667 * s, 16 * s, 37 * s)
  ..cubicTo(16 * s, 32 * s, 18 * s, 27 * s, 22 * s, 24 * s)
  ..cubicTo(22 * s, 23.333 * s, 22 * s, 22.667 * s, 22 * s, 22 * s)
  ..cubicTo(20.667 * s, 22 * s, 19.333 * s, 22 * s, 18 * s, 22 * s)
  ..cubicTo(18 * s, 20 * s, 18 * s, 18 * s, 18 * s, 16 * s)
  ..cubicTo(19.333 * s, 16 * s, 20.667 * s, 16 * s, 22 * s, 16 * s)
  ..cubicTo(22 * s, 14.667 * s, 22 * s, 13.333 * s, 22 * s, 12 * s)
  ..close();

/// The warm specular highlight, in grid units.
///
/// Emitted as LTWH rather than as a centre and radii because `Rect.fromCenter`
/// is not a const constructor, and this file must be entirely const.
const Rect kMarkHighlight = Rect.fromLTWH(
  25.067,
  35.614,
  7.428,
  10.4,
);

/// The meniscus arc: start, end, radius, stroke width and opacity.
const Offset kMarkMeniscusFrom = Offset(27.543, 50.719);
const Offset kMarkMeniscusTo = Offset(31.257, 54.929);
const double kMarkMeniscusRadius = 4.705;
const double kMarkMeniscusWidth = 0.99;
const double kMarkMeniscusOpacity = 0.18;
