// GENERATED by tools/brand/generate.py — do not edit by hand.
//
// The Lacteva mark, in Dart (LACTEVA-BRAND-002 geometry, BRAND-003 rendering).
// `tools/brand/check_inline.py` regenerates this file and compares it, so an
// edit here is a build failure rather than a second mark.
import 'dart:ui';

/// The drop's tight bounding box in the 64 grid the geometry is authored in.
const Rect kMarkBounds = Rect.fromLTWH(
  18.999,
  11.632,
  26.001,
  37.268,
);

/// The drop outline, in grid units scaled by [s].
Path lactevaDropPath(double s) => Path()
  ..moveTo(30.69 * s, 13.229 * s)
  ..cubicTo(32 * s, 11.1 * s, 32 * s, 11.1 * s, 33.31 * s, 13.229 * s)
  ..cubicTo(35.613 * s, 19.1 * s, 38.866 * s, 24.386 * s, 43.071 * s, 29.085 * s)
  ..cubicTo(46.426 * s, 34.537 * s, 45.314 * s, 41.619 * s, 40.449 * s, 45.78 * s)
  ..cubicTo(35.585 * s, 49.94 * s, 28.415 * s, 49.94 * s, 23.551 * s, 45.78 * s)
  ..cubicTo(18.686 * s, 41.619 * s, 17.574 * s, 34.537 * s, 20.929 * s, 29.085 * s)
  ..cubicTo(25.134 * s, 24.386 * s, 28.387 * s, 19.1 * s, 30.69 * s, 13.229 * s)
  ..close();

/// The warm specular highlight, in grid units.
///
/// Emitted as LTWH rather than as a centre and radii because `Rect.fromCenter`
/// is not a const constructor, and this file must be entirely const.
const Rect kMarkHighlight = Rect.fromLTWH(
  20.445,
  20.423,
  12.38,
  17.334,
);

/// The meniscus arc: start, end, radius, stroke width and opacity.
const Offset kMarkMeniscusFrom = Offset(24.571, 45.598);
const Offset kMarkMeniscusTo = Offset(30.762, 52.614);
const double kMarkMeniscusRadius = 7.841;
const double kMarkMeniscusWidth = 1.651;
const double kMarkMeniscusOpacity = 0.18;
