"""The receivable chain, executed (DEMO-015).

    CUSTOMER → DELIVERY → DAILY REPORT → MONTHLY BILL → PAYMENT → RECEIPT
                                                              → STATEMENT

DEMO-009 built every one of those tables and DEMO-013 made them speak rupees.
Neither ran the chain end to end on **PostgreSQL** with a month of real
deliveries in it, and this repository's whole history says that is the gap
where defects live: four work orders that did nothing but execute already
reviewed guarantees found fourteen.

So this is not a test of new code. It is the daily working life of an Indian
dairy — thirty-one days of milk to four customers, a bill, a part payment, a
receipt and a statement — driven through the platform's own API, with every
arithmetic invariant DEMO-015 §22 names asserted against what the database
actually returns.

What it proves, and why each one is worth a step:

  1. the client cannot price milk — the amount is the domain's, not the caller's
  2. a day belongs to the dairy's calendar, not to UTC's
  3. the daily report's totals are the database's, not a page's
  4. a month's bill is exactly its deliveries, to the paisa
  5. the same milk cannot be billed twice
  6. a part payment moves the balance by exactly what was paid
  7. the receipt is the payment, generated by a consumer from the durable log
  8. the statement reconciles: opening + bills - payments = outstanding
  9. a cancelled invoice releases its milk and leaves no money behind
 10. another tenant's customer is a 404, never a 403

Run it directly against any database:

    LACTEVA_DATABASE_URL=postgresql+asyncpg://... \\
      python infra/ci/sales_chain_proof.py out.json

or let `infra/ci/verify-postgres.sh` do it as part of the nine-step proof,
which is where it earns its keep — the suites run on SQLite, and a guarantee
tested only on SQLite is untested.
"""

import asyncio
import json
import os
import pathlib
import re
import sys
from datetime import date, timedelta
from decimal import Decimal

from httpx import ASGITransport, AsyncClient

PASSWORD = os.environ.get("SEED_PASSWORD", "correct-horse-battery")

#: The dairy this proof runs. India, because the platform's own demo tenant is
#: Indian and because Asia/Kolkata is UTC+5:30 — the offset that makes "today"
#: a real question rather than a formality. Nothing here branches on it.
COUNTRY = os.environ.get("PROOF_COUNTRY", "IN")

#: Four customers of the kinds a Bengaluru cooperative actually serves, and a
#: month of milk. The quantities differ per customer per day on purpose: a
#: proof where every line is the same number cannot tell a correct sum from a
#: multiplication.
CUSTOMERS = [
    # (code suffix, name, type, litres/day, rate)
    ("H1", "Sharma Household", "household", Decimal("1.500"), Decimal("56.0000")),
    ("S1", "Adiga Tiffin Room", "shop", Decimal("10.000"), Decimal("52.0000")),
    ("T1", "Hotel Sagar Deluxe", "hotel", Decimal("18.250"), Decimal("50.0000")),
    ("D1", "Nandini Distributors", "distributor", Decimal("50.000"), Decimal("46.5000")),
]

FAILURES: list[str] = []


def check(condition: bool, what: str, detail: str = "") -> None:
    """Record rather than raise.

    A proof that stops at the first failure reports one defect per run, and
    the interesting question is always how many there are.
    """
    if condition:
        print(f"    ok    {what}")
    else:
        print(f"    FAIL  {what}  {detail}")
        FAILURES.append(f"{what} — {detail}" if detail else what)


def money(value) -> Decimal:
    return Decimal(str(value))


async def expect(response, *codes: int, what: str):
    if response.status_code not in codes:
        raise SystemExit(f"sales chain failed at {what}: {response.status_code} {response.text[:400]}")
    return response.json() if response.content else {}


async def _invite_token(client, *, headers: dict, email: str, role_name: str) -> str:
    """Read the invitation token out of the delivered message, as an invitee does.

    SEC-003 removed the raw token from the invite response, so the only way to
    obtain one is the notification channel. Exercising that boundary is the
    point: if the invitation email ever stopped carrying a working token, this
    proof would fail here rather than pass with a dairy nobody could sign into.
    """
    from platform_core.modules.notification import providers

    captured: dict[str, str] = {}

    class _Capturing:
        name = "sales-proof-capture-email"

        async def send(self, message):
            captured["body"] = message.body
            return providers.DeliveryResult(
                provider_message_id=f"proof:{message.notification_id}",
                status=providers.ACCEPTED,
            )

    previous = providers.get_provider("email")
    providers.register_provider("email", _Capturing())
    try:
        await expect(
            await client.post(
                "/v1/invitations",
                json={"email": email, "role_name": role_name},
                headers=headers,
            ),
            201,
            what=f"invite {email}",
        )
    finally:
        providers.register_provider("email", previous)

    match = re.search(r"registration:\s*(\S+?)\.\s", captured.get("body", ""))
    if not match:
        raise SystemExit(f"no invitation token in the message sent to {email}")
    return match.group(1)


async def _bootstrap() -> None:
    """What the app lifespan would do, minus the background loops."""
    from platform_core.core.rls import platform_factory
    from platform_core.modules.authz.service import AuthzService
    from platform_core.modules.event_relay.consumers import discover_consumers
    from platform_core.modules.event_relay.projections import discover_projections

    discover_consumers()
    discover_projections()
    async with platform_factory("sales chain proof: system roles")() as session:
        await AuthzService(session).ensure_system_roles()
        await session.commit()


async def _grant_platform_admin(email: str) -> None:
    from sqlalchemy import select

    from platform_core.core.rls import platform_factory
    from platform_core.modules.authz.models import Role, UserRole
    from platform_core.modules.identity.models import User

    async with platform_factory("sales chain proof: grant platform-admin")() as session:
        user = await session.scalar(select(User).where(User.email == email))
        role = await session.scalar(select(Role).where(Role.name == "platform-admin"))
        session.add(UserRole(user_id=user.id, role_id=role.id, tenant_id=None))
        await session.commit()


async def _run_consumers(times: int = 3) -> None:
    """Drive the Relay to completion.

    The receipt is produced by a CONSUMER reading the durable log, never by
    the payment request. Running the consumers explicitly — rather than
    starting the app's background loop — keeps this script's sessions from
    interleaving with the work it is measuring.
    """
    from platform_core.core.rls import platform_factory
    from platform_core.modules.event_relay.consumers import ConsumerRunner

    runner = ConsumerRunner(platform_factory("sales chain proof: drive consumers"))
    for _ in range(times):
        await runner.run_once()


async def run() -> dict:
    from platform_core.main import create_app

    await _bootstrap()
    app = create_app()

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://sales-proof") as c:
        # --- 0. a dairy, in one country ----------------------------------
        print("\n==> 0  an Indian dairy, onboarded by country alone")
        await expect(
            await c.post(
                "/v1/auth/register",
                json={"email": "root@sales.example", "password": PASSWORD, "full_name": "Root"},
            ),
            201,
            what="register root",
        )
        await _grant_platform_admin("root@sales.example")
        pair = await expect(
            await c.post(
                "/v1/auth/token",
                json={"email": "root@sales.example", "password": PASSWORD},
            ),
            200,
            what="root login",
        )
        root = {"Authorization": f"Bearer {pair['access_token']}"}

        org = await expect(
            await c.post(
                "/v1/organizations",
                json={"name": "Nandini Dairy Proof", "slug": "sales-proof", "country_code": COUNTRY},
                headers=root,
            ),
            201,
            what="create organization",
        )
        currency = org["currency_code"]
        timezone = org["timezone"]
        check(currency == "INR", "the country decided the currency", currency)
        check(timezone == "Asia/Kolkata", "the country decided the clock", timezone)

        token = await _invite_token(
            c,
            headers={**root, "X-Tenant-ID": org["id"]},
            email="manager@sales.example",
            role_name="tenant-admin",
        )
        await expect(
            await c.post(
                "/v1/invitations/accept",
                json={"token": token, "password": PASSWORD, "full_name": "Priya Raghavan"},
            ),
            201,
            what="accept invitation",
        )
        pair = await expect(
            await c.post(
                "/v1/auth/token",
                json={
                    "email": "manager@sales.example",
                    "password": PASSWORD,
                    "tenant_id": org["id"],
                },
            ),
            200,
            what="manager login",
        )
        h = {"Authorization": f"Bearer {pair['access_token']}"}

        # --- 1. customers, each with an agreed rate -----------------------
        print("\n==> 1  four customers, each with a standing plan")
        customers = []
        for code, name, ctype, litres, rate in CUSTOMERS:
            cust = await expect(
                await c.post(
                    "/v1/customers",
                    json={
                        "code": f"CUST-{code}",
                        "name": name,
                        "customer_type": ctype,
                        "phone": f"+9198450001{code[-1]}0",
                        "address": "Bengaluru",
                    },
                    headers=h,
                ),
                201,
                what=f"create customer {code}",
            )
            check(
                cust["currency"] == currency,
                f"{code} bills in the organization's currency without being told",
                cust["currency"],
            )
            plan = await expect(
                await c.post(
                    f"/v1/customers/{cust['id']}/plan",
                    json={
                        "product": "RAW-COW-MILK",
                        "default_quantity": str(litres),
                        "unit_price": str(rate),
                        "effective_from": str(date(2026, 8, 1)),
                    },
                    headers=h,
                ),
                201,
                what=f"plan for {code}",
            )
            customers.append({**cust, "plan": plan, "litres": litres, "rate": rate})

        # --- 2. a month of milk -------------------------------------------
        print("\n==> 2  thirty-one days of deliveries")
        period_from, period_to = date(2026, 8, 1), date(2026, 8, 31)
        expected_total = {cu["id"]: Decimal("0.00") for cu in customers}
        expected_litres = {cu["id"]: Decimal("0.000") for cu in customers}
        recorded = 0
        day = period_from
        while day <= period_to:
            for index, cu in enumerate(customers):
                # Vary the round: households skip Sundays, the hotel takes an
                # extra half-litre at the weekend. A month where every day is
                # identical would not notice a report that dropped one.
                quantity = cu["litres"]
                if cu["customer_type"] == "household" and day.weekday() == 6:
                    status = "skipped"
                    quantity = Decimal("0.000")
                else:
                    status = "delivered"
                    if cu["customer_type"] == "hotel" and day.weekday() >= 5:
                        quantity = quantity + Decimal("0.500")
                body = {
                    "customer_id": cu["id"],
                    "delivery_date": str(day),
                    "slot": "morning",
                    "quantity": str(quantity),
                    "status": status,
                    # DEMO-015 §5: the client tries to price its own milk.
                    # These fields are not on the command, so they must be
                    # ignored — step 3 checks that they were.
                    "amount": "1.00",
                    "unit_price": "0.0001",
                    "currency": "KES",
                }
                delivery = await expect(
                    await c.post("/v1/deliveries", json=body, headers=h),
                    201,
                    what=f"delivery {cu['code']} {day}",
                )
                recorded += 1
                if index == 0 and day == period_from:
                    first_delivery = delivery
                if status == "delivered":
                    expected_total[cu["id"]] += money(delivery["amount"])
                    expected_litres[cu["id"]] += money(delivery["quantity"])
            day += timedelta(days=1)
        print(f"    {recorded} deliveries recorded")

        # --- 3. the client did not get to price the milk -------------------
        print("\n==> 3  the amount is the domain's, not the caller's")
        first = customers[0]
        check(
            money(first_delivery["unit_price"]) == first["rate"],
            "the rate came from the customer's plan",
            f"{first_delivery['unit_price']} vs {first['rate']}",
        )
        check(
            money(first_delivery["amount"]) == money(first_delivery["quantity"]) * first["rate"],
            "amount = quantity x plan rate, computed by the server",
            first_delivery["amount"],
        )
        check(
            first_delivery["currency"] == currency,
            "the delivery is in the organization's currency, not the client's",
            first_delivery["currency"],
        )
        check(
            money(first_delivery["amount"]) != Decimal("1.00"),
            "the amount the client sent was ignored",
            first_delivery["amount"],
        )

        # --- 4. the daily report ------------------------------------------
        print("\n==> 4  the daily report totals in the database")
        one_day = await expect(
            await c.get(
                "/v1/deliveries/report",
                params={"date_from": str(period_from), "date_to": str(period_from)},
                headers=h,
            ),
            200,
            what="one-day report",
        )
        # 1 Aug 2026 is a Saturday: the household delivers, the hotel takes its
        # weekend extra. Four customers, four deliveries.
        check(one_day["deliveries"] == 4, "four deliveries on the first", one_day["deliveries"])
        check(one_day["customers_served"] == 4, "four customers served", one_day["customers_served"])

        month = await expect(
            await c.get(
                "/v1/deliveries/report",
                params={"date_from": str(period_from), "date_to": str(period_to)},
                headers=h,
            ),
            200,
            what="month report",
        )
        check(
            money(month["total_amount"]) == sum(expected_total.values()),
            "the month's value is the sum of its deliveries",
            f"{month['total_amount']} vs {sum(expected_total.values())}",
        )
        check(
            money(month["total_quantity"]) == sum(expected_litres.values()),
            "the month's volume is the sum of its deliveries",
            f"{month['total_quantity']} vs {sum(expected_litres.values())}",
        )
        check(
            len(month["by_day"]) == 31,
            "every day of the month appears",
            str(len(month["by_day"])),
        )
        check(
            month["skipped"] == 5,  # five Sundays in August 2026, one household
            "the skipped rounds are counted and not billed",
            str(month["skipped"]),
        )

        # --- 5. the monthly bill ------------------------------------------
        print("\n==> 5  the monthly bill is exactly its deliveries")
        target = customers[1]  # the tiffin room: no skips, a flat rate
        invoice = await expect(
            await c.post(
                "/v1/invoices",
                json={
                    "customer_id": target["id"],
                    "period_from": str(period_from),
                    "period_to": str(period_to),
                },
                headers=h,
            ),
            201,
            what="generate invoice",
        )
        check(
            money(invoice["total"]) == expected_total[target["id"]],
            "the bill totals the month's milk to the paisa",
            f"{invoice['total']} vs {expected_total[target['id']]}",
        )
        check(invoice["currency"] == currency, "the bill is in rupees", invoice["currency"])
        check(invoice["status"] == "draft", "a new bill is a draft", invoice["status"])
        check(invoice["line_count"] == 31, "one line per delivery", str(invoice["line_count"]))

        detail = await expect(
            await c.get(f"/v1/invoices/{invoice['id']}", headers=h), 200, what="invoice detail"
        )
        line_sum = sum(money(line["amount"]) for line in detail["lines"])
        check(
            line_sum == money(invoice["total"]),
            "the lines add up to the total",
            f"{line_sum} vs {invoice['total']}",
        )

        # --- 6. the same milk cannot be billed twice ----------------------
        print("\n==> 6  the same milk cannot be billed twice")
        again = await c.post(
            "/v1/invoices",
            json={
                "customer_id": target["id"],
                "period_from": str(period_from),
                "period_to": str(period_to),
            },
            headers=h,
        )
        check(again.status_code == 409, "a second bill for the same period is refused", str(again.status_code))

        overlapping = await c.post(
            "/v1/invoices",
            json={
                "customer_id": target["id"],
                "period_from": str(period_from),
                "period_to": str(period_from + timedelta(days=9)),
            },
            headers=h,
        )
        check(
            overlapping.status_code == 409,
            "an overlapping period finds no unbilled milk and is refused",
            str(overlapping.status_code),
        )

        issued = await expect(
            await c.post(f"/v1/invoices/{invoice['id']}/issue", json={}, headers=h),
            200,
            what="issue invoice",
        )
        check(issued["status"] == "issued", "the bill was issued", issued["status"])

        # --- 7. a part payment --------------------------------------------
        print("\n==> 7  a part payment moves the balance by what was paid")
        before = await expect(
            await c.get(f"/v1/customers/{target['id']}/balance", headers=h),
            200,
            what="balance before",
        )
        part = money(invoice["total"]) / 2
        part = part.quantize(Decimal("0.01"))
        payment = await expect(
            await c.post(
                "/v1/customer-payments",
                json={
                    "customer_id": target["id"],
                    "amount": str(part),
                    "method": "CASH",
                    "reference": "counter",
                    "invoice_ids": [invoice["id"]],
                },
                headers=h,
            ),
            201,
            what="record part payment",
        )
        check(
            money(payment["amount"]) == part and payment["currency"] == currency,
            "the payment is in the customer's own currency",
            f"{payment['amount']} {payment['currency']}",
        )
        after = await expect(
            await c.get(f"/v1/customers/{target['id']}/balance", headers=h),
            200,
            what="balance after",
        )
        check(
            money(before["outstanding"]) - money(after["outstanding"]) == part,
            "outstanding fell by exactly the amount paid",
            f"{before['outstanding']} - {after['outstanding']} vs {part}",
        )

        invoice_now = await expect(
            await c.get(f"/v1/invoices/{invoice['id']}", headers=h), 200, what="invoice after part"
        )
        check(
            invoice_now["invoice"]["status"] == "issued",
            "a half-paid bill is not paid",
            invoice_now["invoice"]["status"],
        )

        # --- 8. the receipt is generated from the log ---------------------
        print("\n==> 8  the receipt is produced by a consumer, from the event")
        await _run_consumers()
        receipts = await expect(
            await c.get("/v1/customer-receipts", params={"customer_id": target["id"]}, headers=h),
            200,
            what="receipts",
        )
        items = receipts.get("items", [])
        check(len(items) == 1, "one payment produced exactly one receipt", str(len(items)))
        if items:
            receipt = items[0]
            check(
                money(receipt["amount"]) == part,
                "the receipt says what was actually paid",
                receipt["amount"],
            )
            check(
                receipt["currency"] == currency,
                "the receipt is in rupees",
                receipt["currency"],
            )
            check(
                receipt["payment_number"] == payment["payment_number"],
                "the receipt names its payment",
                receipt["payment_number"],
            )

        # --- 9. the rest of the money -------------------------------------
        print("\n==> 9  paying the rest closes the bill")
        rest = money(invoice["total"]) - part
        await expect(
            await c.post(
                "/v1/customer-payments",
                json={
                    "customer_id": target["id"],
                    "amount": str(rest),
                    "method": "BANK_TRANSFER",
                    "reference": "NEFT-0001",
                    "invoice_ids": [invoice["id"]],
                },
                headers=h,
            ),
            201,
            what="record balance payment",
        )
        settled = await expect(
            await c.get(f"/v1/invoices/{invoice['id']}", headers=h), 200, what="invoice settled"
        )
        check(
            settled["invoice"]["status"] == "paid",
            "a fully paid bill says so",
            settled["invoice"]["status"],
        )
        final = await expect(
            await c.get(f"/v1/customers/{target['id']}/balance", headers=h),
            200,
            what="balance final",
        )
        check(
            money(final["outstanding"]) == Decimal("0.00"),
            "nothing is owed once the bill is paid",
            final["outstanding"],
        )

        # --- 10. a cancelled bill leaves no money behind -------------------
        print("\n==> 10  a cancelled draft releases its milk")
        spare = customers[2]  # the hotel, still unbilled
        draft = await expect(
            await c.post(
                "/v1/invoices",
                json={
                    "customer_id": spare["id"],
                    "period_from": str(period_from),
                    "period_to": str(period_to),
                },
                headers=h,
            ),
            201,
            what="draft for the hotel",
        )
        cancelled = await expect(
            await c.post(
                f"/v1/invoices/{draft['id']}/cancel",
                json={"reason": "wrong period"},
                headers=h,
            ),
            200,
            what="cancel draft",
        )
        check(cancelled["status"] == "cancelled", "the draft is cancelled", cancelled["status"])
        balance_after_cancel = await expect(
            await c.get(f"/v1/customers/{spare['id']}/balance", headers=h),
            200,
            what="balance after cancel",
        )
        check(
            money(balance_after_cancel["invoiced"]) == Decimal("0.00"),
            "a cancelled bill is not money owed",
            balance_after_cancel["invoiced"],
        )
        check(
            money(balance_after_cancel["unbilled_amount"]) == expected_total[spare["id"]],
            "its milk went back to being unbilled and can be billed again",
            f"{balance_after_cancel['unbilled_amount']} vs {expected_total[spare['id']]}",
        )
        rebilled = await c.post(
            "/v1/invoices",
            json={
                "customer_id": spare["id"],
                "period_from": str(period_from),
                "period_to": str(period_to),
            },
            headers=h,
        )
        check(
            rebilled.status_code == 201,
            "the same period can be billed again after a cancellation",
            str(rebilled.status_code),
        )

        # --- 11. another dairy cannot see any of it ------------------------
        print("\n==> 11  another dairy sees a 404, never a 403")
        await expect(
            await c.post(
                "/v1/auth/register",
                json={"email": "root2@sales.example", "password": PASSWORD, "full_name": "Other"},
            ),
            201,
            what="register other root",
        )
        await _grant_platform_admin("root2@sales.example")
        pair2 = await expect(
            await c.post(
                "/v1/auth/token",
                json={"email": "root2@sales.example", "password": PASSWORD},
            ),
            200,
            what="other root login",
        )
        root2 = {"Authorization": f"Bearer {pair2['access_token']}"}
        other = await expect(
            await c.post(
                "/v1/organizations",
                json={"name": "Rift Valley Proof", "slug": "sales-proof-ke", "country_code": "KE"},
                headers=root2,
            ),
            201,
            what="create other organization",
        )
        token2 = await _invite_token(
            c,
            headers={**root2, "X-Tenant-ID": other["id"]},
            email="manager@other.example",
            role_name="tenant-admin",
        )
        await expect(
            await c.post(
                "/v1/invitations/accept",
                json={"token": token2, "password": PASSWORD, "full_name": "Wanjiku"},
            ),
            201,
            what="accept other invitation",
        )
        pair2 = await expect(
            await c.post(
                "/v1/auth/token",
                json={
                    "email": "manager@other.example",
                    "password": PASSWORD,
                    "tenant_id": other["id"],
                },
            ),
            200,
            what="other manager login",
        )
        h2 = {"Authorization": f"Bearer {pair2['access_token']}"}

        check(other["currency_code"] == "KES", "the Kenyan dairy still bills in shillings", other["currency_code"])
        for what, response in (
            ("customer", await c.get(f"/v1/customers/{target['id']}", headers=h2)),
            ("invoice", await c.get(f"/v1/invoices/{invoice['id']}", headers=h2)),
            ("balance", await c.get(f"/v1/customers/{target['id']}/balance", headers=h2)),
        ):
            check(
                response.status_code == 404,
                f"another dairy's {what} does not exist",
                str(response.status_code),
            )
        their_deliveries = await expect(
            await c.get("/v1/deliveries", headers=h2), 200, what="other deliveries"
        )
        check(
            their_deliveries["total"] == 0,
            "and their delivery list is empty rather than someone else's",
            str(their_deliveries["total"]),
        )

        return {
            "organization": org["id"],
            "currency": currency,
            "timezone": timezone,
            "customers": len(customers),
            "deliveries": recorded,
            "month_quantity": month["total_quantity"],
            "month_amount": month["total_amount"],
            "invoice": invoice["invoice_number"],
            "invoice_total": invoice["total"],
            "payment": payment["payment_number"],
            "receipt": items[0]["receipt_number"] if items else None,
            "failures": FAILURES,
        }


async def main() -> None:
    summary = await run()
    print("\n=== the chain ===")
    for key, value in summary.items():
        if key != "failures":
            print(f"  {key:18} {value}")
    if len(sys.argv) > 1:
        pathlib.Path(sys.argv[1]).write_text(json.dumps(summary, indent=2, default=str))
    if FAILURES:
        print(f"\n{len(FAILURES)} FAILURES:")
        for failure in FAILURES:
            print(f"  - {failure}")
        raise SystemExit(1)
    print("\nthe receivable chain holds")


if __name__ == "__main__":
    asyncio.run(main())
