#!/usr/bin/env python3
"""Generate docs/XREF.md — the automatic document cross-reference map.

Scans every markdown file for document-ID mentions (PREFIX-NNNN) and
front-matter `related:` entries, then emits, per document: outbound
references (what it cites) and inbound references (what cites it).

The output file is AUTO-GENERATED — never edit it by hand; re-run this
script instead (same PR as any document change that alters references):

    python3 tools/xref/generate_xref.py [--root <repo-root>] [--check]

--check: exit 1 if docs/XREF.md is out of date (for CI), without writing.
"""
import argparse
import os
import re
import sys

DOC_ID_RE = re.compile(r"\b([A-Z]{2,4}-\d{4})\b")
FILE_ID_RE = re.compile(r"^([A-Z]{2,4}-\d{4})-")
FENCE_RE = re.compile(r"```.*?```", re.S)
TITLE_RE = re.compile(r"^title:\s*(.+)$", re.M)

HEADER = """---
id: XREF
title: Automatic Document Cross-Reference Map
type: reference
status: Approved
version: "1.0"
owner: Documentation Engineering
created: 2026-08-02
last-updated: {date}
---

# Automatic Document Cross-Reference Map

**AUTO-GENERATED by `tools/xref/generate_xref.py` — do not edit by hand.**
Regenerate in the same PR as any change that adds or removes document-ID
references. Complements the rule-focused
[architecture cross-reference index](03-architecture/CROSS-REFERENCE.md):
that document says which references are *legal*; this map records which
references *exist*.

Mentions are counted from prose and front matter (code blocks excluded);
self-references and a template's references to its own examples are ignored.

"""


def collect(root):
    docs = {}   # id -> {path, title}
    refs = {}   # id -> set of ids it mentions
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".git")]
        for f in filenames:
            if not f.endswith(".md"):
                continue
            path = os.path.join(dirpath, f)
            rel = os.path.relpath(path, root)
            text = open(path, encoding="utf-8").read()
            m = FILE_ID_RE.match(f)
            doc_id = m.group(1) if m else None
            if doc_id:
                tm = TITLE_RE.search(text.split("---")[1]) \
                    if text.startswith("---") and len(text.split("---")) > 2 \
                    else None
                docs[doc_id] = {
                    "path": rel.replace(os.sep, "/"),
                    "title": tm.group(1).strip() if tm else f,
                }
                mentioned = set(DOC_ID_RE.findall(FENCE_RE.sub("", text)))
                mentioned.discard(doc_id)
                refs[doc_id] = mentioned
    # keep only references to documents that exist
    for d in refs:
        refs[d] = {r for r in refs[d] if r in docs}
    return docs, refs


def render(docs, refs, date):
    inbound = {d: set() for d in docs}
    for src, targets in refs.items():
        for t in targets:
            inbound[t].add(src)

    out = [HEADER.format(date=date)]
    out.append("## Reference Map\n")
    out.append("| Document | Outbound (cites) | Inbound (cited by) |")
    out.append("| --- | --- | --- |")
    for d in sorted(docs):
        link = f"[{d}]({docs[d]['path'].removeprefix('docs/')})"
        ob = ", ".join(sorted(refs.get(d, ()))) or "—"
        ib = ", ".join(sorted(inbound.get(d, ()))) or "—"
        out.append(f"| {link} | {ob} | {ib} |")

    fan_in = sorted(((len(v), k) for k, v in inbound.items()), reverse=True)
    out.append("\n## Highest Fan-In (change-risk concentrators)\n")
    out.append("| Document | Inbound Count |")
    out.append("| --- | --- |")
    for count, d in fan_in[:10]:
        if count == 0:
            break
        out.append(f"| {d} — {docs[d]['title']} | {count} |")

    orphans = [d for d in sorted(docs)
               if not inbound[d] and not refs.get(d)]
    out.append("\n## Unreferenced Documents\n")
    out.append(", ".join(orphans) if orphans else
               "None — every ID-bearing document is connected.")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    root = args.root or os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    target = os.path.join(root, "docs", "XREF.md")

    docs, refs = collect(root)
    # stable date: reuse existing file's last-updated when content unchanged
    date = "2026-08-02"
    existing = open(target, encoding="utf-8").read() \
        if os.path.exists(target) else ""
    dm = re.search(r"^last-updated:\s*(\S+)", existing, re.M)
    if dm:
        date = dm.group(1)
    content = render(docs, refs, date)

    if args.check:
        if content != existing:
            print("XREF.md is out of date — run tools/xref/generate_xref.py")
            return 1
        print("XREF.md is current.")
        return 0
    open(target, "w", encoding="utf-8").write(content)
    print(f"Wrote {os.path.relpath(target, root)}: "
          f"{len(docs)} documents mapped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
