"""The sales side of the dashboard, executed (DEMO-010).

DEMO-009 proved the workflow. This proves the numbers a MANAGER sees on top of
it, which is a different claim and fails differently: a per-customer figure is
wrong loudly, a dashboard figure is wrong quietly and stays on screen.

Two properties are checked repeatedly.

**The aggregate agrees with the parts.** `sales_summary().receivable` must
equal the sum of `/customers/{id}/balance` over every customer, and
`receivables().total_outstanding` must equal it too. Three routes, one debt.

**The totals are computed across the whole match, not the page.** A page total
understates the debt of any dairy with more households than fit on a screen —
the exact bug that makes a demo look fine and a real deployment lie. So the
tests below deliberately create more customers than the page size and assert
on the figure the manager reads first.
"""

from datetime import date, timedelta
from decimal import Decimal

from tests.test_org_structure import _tenant_admin
from tests.test_payments import _second_tenant

TODAY = date(2026, 8, 12)


async def _customer(client, admin, name, rate="60.0000", quantity="2.000"):
    r = await client.post(
        "/v1/customers",
        json={
            "name": name,
            "customer_type": "household",
            "plan": {
                "product": "RAW-COW-MILK",
                "default_quantity": quantity,
                "quantity_unit": "L",
                "unit_price": rate,
            },
        },
        headers=admin,
    )
    assert r.status_code == 201, r.text
    return r.json()


async def _deliver(client, admin, customer_id, days, *, status="delivered"):
    """`days` consecutive days ending TODAY. Returns what they are worth."""
    total = Decimal("0.00")
    for offset in range(days):
        r = await client.post(
            "/v1/deliveries",
            json={
                "customer_id": customer_id,
                "delivery_date": str(TODAY - timedelta(days=offset)),
                "slot": "morning",
                "status": status,
            },
            headers=admin,
        )
        assert r.status_code == 201, r.text
        total += Decimal(r.json()["amount"])
    return total


async def _bill(client, admin, customer_id, days, *, issue=True):
    r = await client.post(
        "/v1/invoices",
        json={
            "customer_id": customer_id,
            "period_from": str(TODAY - timedelta(days=days - 1)),
            "period_to": str(TODAY),
        },
        headers=admin,
    )
    assert r.status_code == 201, r.text
    invoice = r.json()
    if issue:
        r = await client.post(f"/v1/invoices/{invoice['id']}/issue", json={}, headers=admin)
        assert r.status_code == 200, r.text
        invoice = r.json()
    return invoice


async def _pay(client, admin, customer_id, amount):
    r = await client.post(
        "/v1/customer-payments",
        json={"customer_id": customer_id, "amount": str(amount), "method": "CASH"},
        headers=admin,
    )
    assert r.status_code == 201, r.text
    return r.json()


async def _ledger(client):
    """A dairy in every state a real one is in at once.

    Fully paid, part paid, unpaid, and delivered-but-unbilled — because a
    summary that is only ever exercised against settled accounts cannot
    demonstrate that it distinguishes them.
    """
    _org, admin = await _tenant_admin(client)
    paid = await _customer(client, admin, "Fully Paid Household")
    part = await _customer(client, admin, "Part Paid Household")
    unpaid = await _customer(client, admin, "Unpaid Household")
    unbilled = await _customer(client, admin, "Delivered Not Billed")

    worth = {}
    for customer in (paid, part, unpaid, unbilled):
        worth[customer["id"]] = await _deliver(client, admin, customer["id"], 5)

    await _bill(client, admin, paid["id"], 5)
    await _bill(client, admin, part["id"], 5)
    await _bill(client, admin, unpaid["id"], 5)
    # `unbilled` is deliberately left off any bill.

    await _pay(client, admin, paid["id"], worth[paid["id"]])
    await _pay(client, admin, part["id"], Decimal("100.00"))

    # Receipts are generated by a consumer reading the durable event log, not
    # by the payment call — so a ledger that never runs the relay has payments
    # with no receipts, which is not the state a real dairy is ever in.
    from platform_core.core.rls import platform_factory
    from platform_core.modules.event_relay.consumers import ConsumerRunner

    await ConsumerRunner(platform_factory("test: run consumers")).run_once()
    return admin, {"paid": paid, "part": part, "unpaid": unpaid, "unbilled": unbilled}, worth


# --- the summary --------------------------------------------------------------


async def test_the_sales_summary_reports_what_actually_went_out(client):
    admin, _who, worth = await _ledger(client)
    summary = (
        await client.get(
            f"/v1/reports/sales/summary?date_from={TODAY - timedelta(days=4)}&date_to={TODAY}",
            headers=admin,
        )
    ).json()

    assert summary["deliveries_in_period"] == 20  # four households, five days
    assert Decimal(summary["delivered_quantity_in_period"]) == Decimal("40.000")
    assert Decimal(summary["sales_value_in_period"]) == sum(worth.values())
    assert summary["customers_served_in_period"] == 4
    assert summary["active_customers"] == 4
    assert summary["quantity_unit"] == "L"
    assert summary["currency"] == "KES"


async def test_a_cancelled_delivery_is_worth_nothing_to_the_sales_figure(client):
    """Milk that never reached the customer must not inflate revenue."""
    _org, admin = await _tenant_admin(client)
    customer = await _customer(client, admin, "Cancelled Deliveries Household")
    delivered = await _deliver(client, admin, customer["id"], 3)
    r = await client.post(
        "/v1/deliveries",
        json={
            "customer_id": customer["id"],
            "delivery_date": str(TODAY - timedelta(days=5)),
            "slot": "morning",
            "status": "cancelled",
        },
        headers=admin,
    )
    assert r.status_code == 201, r.text
    assert Decimal(r.json()["amount"]) == Decimal("0.00")

    summary = (
        await client.get(
            f"/v1/reports/sales/summary?date_from={TODAY - timedelta(days=10)}&date_to={TODAY}",
            headers=admin,
        )
    ).json()
    assert summary["deliveries_in_period"] == 3
    assert Decimal(summary["sales_value_in_period"]) == delivered


async def test_the_receivable_equals_the_sum_of_every_customer_balance(client):
    """The dashboard's debt and the customer pages' debt are one number."""
    admin, who, _worth = await _ledger(client)
    summary = (await client.get("/v1/reports/sales/summary", headers=admin)).json()

    by_customer = Decimal("0.00")
    for customer in who.values():
        balance = (
            await client.get(f"/v1/customers/{customer['id']}/balance", headers=admin)
        ).json()
        by_customer += Decimal(balance["outstanding"])

    assert Decimal(summary["receivable"]) == by_customer
    assert Decimal(summary["invoiced"]) - Decimal(summary["received"]) == by_customer
    assert summary["customers_owing"] == 2  # part paid and unpaid; not the settled one


async def test_the_summary_separates_delivered_from_billed(client):
    admin, who, worth = await _ledger(client)
    summary = (await client.get("/v1/reports/sales/summary", headers=admin)).json()

    assert summary["unbilled_deliveries"] == 5
    assert Decimal(summary["unbilled_amount"]) == worth[who["unbilled"]["id"]]
    statuses = {row["status"]: row for row in summary["by_status"]}
    assert statuses["issued"]["count"] == 2  # part paid and unpaid
    assert statuses["paid"]["count"] == 1
    assert summary["open_invoices"] == 2
    assert summary["receipts_issued"] >= 2


async def test_a_balance_is_as_at_now_and_ignores_the_period(client):
    """Asking for one day must not shrink the debt to that day's billing."""
    admin, _who, _worth = await _ledger(client)
    wide = (
        await client.get(
            f"/v1/reports/sales/summary?date_from={TODAY - timedelta(days=30)}&date_to={TODAY}",
            headers=admin,
        )
    ).json()
    one_day = (
        await client.get(
            f"/v1/reports/sales/summary?date_from={TODAY}&date_to={TODAY}", headers=admin
        )
    ).json()

    assert one_day["deliveries_in_period"] < wide["deliveries_in_period"]
    assert Decimal(one_day["receivable"]) == Decimal(wide["receivable"])
    assert Decimal(one_day["invoiced"]) == Decimal(wide["invoiced"])


# --- who owes money -----------------------------------------------------------


async def test_receivables_lists_only_customers_who_owe_worst_first(client):
    admin, who, worth = await _ledger(client)
    page = (await client.get("/v1/reports/receivables", headers=admin)).json()

    names = [row["name"] for row in page["items"]]
    assert names == ["Unpaid Household", "Part Paid Household"]
    assert page["total"] == 2
    # The settled customer is absent, and so is the one who was never billed.
    assert "Fully Paid Household" not in names
    assert "Delivered Not Billed" not in names

    unpaid, part = page["items"]
    assert Decimal(unpaid["outstanding"]) == worth[who["unpaid"]["id"]]
    assert Decimal(part["outstanding"]) == worth[who["part"]["id"]] - Decimal("100.00")
    assert part["last_payment_at"] is not None
    assert unpaid["last_payment_at"] is None
    assert unpaid["open_invoices"] == 1
    assert unpaid["oldest_unpaid_from"] == str(TODAY - timedelta(days=4))


async def test_receivables_can_show_every_customer_not_only_debtors(client):
    admin, _who, _worth = await _ledger(client)
    page = (await client.get("/v1/reports/receivables?owing_only=false", headers=admin)).json()
    assert page["total"] == 4
    assert {row["name"] for row in page["items"]} == {
        "Fully Paid Household",
        "Part Paid Household",
        "Unpaid Household",
        "Delivered Not Billed",
    }
    settled = next(r for r in page["items"] if r["name"] == "Fully Paid Household")
    assert Decimal(settled["outstanding"]) == Decimal("0.00")


async def test_the_outstanding_total_covers_every_match_not_just_the_page(client):
    """The regression that would make a real dairy's debt look small.

    Twelve debtors, a page of five. Summing the page gives five customers'
    worth of debt and looks entirely plausible — which is why it has to be
    asserted rather than eyeballed.
    """
    _org, admin = await _tenant_admin(client)
    expected = Decimal("0.00")
    for n in range(12):
        customer = await _customer(client, admin, f"Debtor {n:02d}", rate=f"{50 + n}.0000")
        expected += await _deliver(client, admin, customer["id"], 3)
        await _bill(client, admin, customer["id"], 3)

    page = (await client.get("/v1/reports/receivables?limit=5", headers=admin)).json()
    assert len(page["items"]) == 5
    assert page["total"] == 12
    assert Decimal(page["total_outstanding"]) == expected
    assert Decimal(page["total_outstanding"]) > sum(
        Decimal(row["outstanding"]) for row in page["items"]
    )

    # And the count is a count of customers, not the square of one — the shape
    # a duplicated subquery produces, which reads as 144 rather than 12.
    everyone = (await client.get("/v1/reports/receivables?limit=100", headers=admin)).json()
    assert everyone["total"] == 12 and len(everyone["items"]) == 12
    assert Decimal(everyone["total_outstanding"]) == expected


async def test_receivables_pages_without_repeating_or_dropping_a_customer(client):
    _org, admin = await _tenant_admin(client)
    for n in range(12):
        customer = await _customer(client, admin, f"Debtor {n:02d}", rate=f"{50 + n}.0000")
        await _deliver(client, admin, customer["id"], 3)
        await _bill(client, admin, customer["id"], 3)

    seen: list[str] = []
    for offset in (0, 5, 10):
        page = (
            await client.get(f"/v1/reports/receivables?limit=5&offset={offset}", headers=admin)
        ).json()
        seen.extend(row["code"] for row in page["items"])
    assert len(seen) == 12 and len(set(seen)) == 12


async def test_receivables_is_searchable_in_the_database(client):
    admin, _who, _worth = await _ledger(client)
    page = (await client.get("/v1/reports/receivables?q=unpaid", headers=admin)).json()
    assert page["total"] == 1 and page["items"][0]["name"] == "Unpaid Household"


# --- the dashboard ------------------------------------------------------------


async def test_the_dashboard_carries_both_sides_of_the_business(client):
    admin, _who, worth = await _ledger(client)
    dash = (
        await client.get(
            f"/v1/reports/dashboard?date_from={TODAY - timedelta(days=4)}&date_to={TODAY}",
            headers=admin,
        )
    ).json()

    assert "collection" in dash and "sales" in dash
    assert Decimal(dash["sales"]["sales_value_in_period"]) == sum(worth.values())
    # And it agrees with the standalone endpoint, because it is the same call.
    standalone = (
        await client.get(
            f"/v1/reports/sales/summary?date_from={TODAY - timedelta(days=4)}&date_to={TODAY}",
            headers=admin,
        )
    ).json()
    assert dash["sales"] == standalone


async def test_what_needs_attention_names_real_sales_states(client):
    admin, _who, _worth = await _ledger(client)
    dash = (await client.get("/v1/reports/dashboard", headers=admin)).json()
    items = {item["key"]: item for item in dash["attention"]}

    assert items["customers_owing"]["count"] == 2
    assert items["unbilled_deliveries"]["count"] == 5
    assert items["customers_owing"]["href"] == "/receivables"
    # Nothing is drafted, so nothing claims to be.
    assert "draft_bills" not in items


async def test_a_quiet_dairy_raises_nothing_and_reports_zero(client):
    """The empty state is a real state, not a crash and not a fake number."""
    _org, admin = await _tenant_admin(client)
    summary = (await client.get("/v1/reports/sales/summary", headers=admin)).json()
    assert summary["deliveries_in_period"] == 0
    assert Decimal(summary["sales_value_in_period"]) == Decimal("0.00")
    assert Decimal(summary["receivable"]) == Decimal("0.00")
    assert summary["by_status"] == []
    assert summary["currency"] is None

    page = (await client.get("/v1/reports/receivables", headers=admin)).json()
    assert page["items"] == [] and page["total"] == 0
    assert Decimal(page["total_outstanding"]) == Decimal("0.00")

    dash = (await client.get("/v1/reports/dashboard", headers=admin)).json()
    assert [
        i["key"] for i in dash["attention"] if i["key"].startswith(("customers", "unbilled"))
    ] == []


# --- tenancy ------------------------------------------------------------------


async def test_one_dairys_receivables_are_invisible_to_another(client):
    """Reporting SELECTs across modules; it must not select across tenants."""
    admin_a, who_a, _worth = await _ledger(client)
    admin_b = await _second_tenant(client)
    await _customer(client, admin_b, "Other Dairy Household")

    theirs = (await client.get("/v1/reports/receivables?owing_only=false", headers=admin_b)).json()
    assert [row["name"] for row in theirs["items"]] == ["Other Dairy Household"]
    assert Decimal(theirs["total_outstanding"]) == Decimal("0.00")

    summary_b = (await client.get("/v1/reports/sales/summary", headers=admin_b)).json()
    assert summary_b["total_customers"] == 1
    assert Decimal(summary_b["receivable"]) == Decimal("0.00")

    summary_a = (await client.get("/v1/reports/sales/summary", headers=admin_a)).json()
    assert summary_a["total_customers"] == len(who_a)
    assert Decimal(summary_a["receivable"]) > Decimal("0.00")
