"""Receipt Engine (RCP-001): automatic generation from completed payments,
immutability, lifecycle, numbering, the rendering abstraction, history,
events, permissions, pagination, tenant isolation.

The environment built by `_receipted` pays a 7897.50 KES settlement in full,
so every amount assertion below is anchored on that number.
"""

import uuid
from decimal import Decimal

import pytest
from sqlalchemy import select

from tests.conftest import register_and_login
from tests.test_payments import (
    _action,
    _create_payment,
    _pay,
    _payable,
    _second_settlement,
    _second_tenant,
    _viewer,
)

FULL = Decimal("7897.50")


@pytest.fixture
def renderer_guard():
    """Restore the renderer registry after tests swap in fakes."""
    from platform_core.modules.receipt import rendering

    yield rendering
    rendering.reset_renderers()


def _runner():
    from platform_core.core import db
    from platform_core.modules.event_relay.consumers import ConsumerRunner

    return ConsumerRunner(db.get_session_factory())


async def _receipts():
    from platform_core.core import db
    from platform_core.modules.receipt.models import Receipt

    async with db.get_session_factory()() as s:
        return list((await s.scalars(select(Receipt).order_by(Receipt.generated_at))).all())


async def _complete_payment(client, headers, payment_id, *, reference="BNK-1"):
    for action, body in (
        ("submit", {}),
        ("execute", {}),
        ("complete", {"reference": reference}),
    ):
        r = await _action(client, headers, payment_id, action, body)
        assert r.status_code == 200, r.text


async def _receipted(client, *, reference="MPESA-77"):
    """A completed payment whose receipt has been generated by the consumer."""
    headers, center, supplier, settlement = await _payable(client)
    payment = await _pay(client, headers, settlement, method="MOBILE_MONEY")
    await _complete_payment(client, headers, payment["id"], reference=reference)
    await _runner().run_once()
    page = (await client.get("/v1/receipts", headers=headers)).json()
    assert page["total"] == 1, page
    return headers, center, supplier, settlement, payment, page["items"][0]


async def _detail(client, headers, receipt_id) -> dict:
    r = await client.get(f"/v1/receipts/{receipt_id}", headers=headers)
    assert r.status_code == 200, r.text
    return r.json()


# --- automatic generation ----------------------------------------------------


async def test_completed_payment_generates_a_receipt(client):
    _headers, _center, supplier, settlement, payment, receipt = await _receipted(client)
    assert receipt["receipt_number"].startswith("RCP-")
    assert receipt["status"] == "generated"
    assert receipt["payment_id"] == payment["id"]
    assert receipt["payment_number"] == payment["payment_number"]
    assert receipt["payment_reference"] == "MPESA-77"
    assert receipt["payment_method"] == "MOBILE_MONEY"
    assert receipt["supplier_id"] == supplier["id"]
    assert receipt["supplier_name"] == "Amina Njoroge"
    assert receipt["supplier_code"] == supplier["code"]
    assert Decimal(receipt["net_amount"]) == FULL
    assert receipt["currency"] == "KES"
    assert receipt["line_count"] == 1
    assert receipt["payment_date"] is not None
    assert settlement["id"]


async def test_an_incomplete_payment_generates_nothing(client):
    """Only COMPLETED payments produce receipts — a draft or failed payment
    proves nothing."""
    headers, _center, _supplier, settlement = await _payable(client)
    payment = await _pay(client, headers, settlement)
    await _action(client, headers, payment["id"], "submit")
    await _action(client, headers, payment["id"], "execute")
    await _action(client, headers, payment["id"], "fail", {"reason": "bounced"})
    await _runner().run_once()
    assert await _receipts() == []
    assert (await client.get("/v1/receipts", headers=headers)).json()["total"] == 0


async def test_cancelled_payment_generates_nothing(client):
    headers, _center, _supplier, settlement = await _payable(client)
    payment = await _pay(client, headers, settlement)
    await _action(client, headers, payment["id"], "cancel", {"reason": "duplicate"})
    await _runner().run_once()
    assert (await client.get("/v1/receipts", headers=headers)).json()["total"] == 0


async def test_receipt_records_the_settlement_line(client):
    headers, center, _supplier, settlement, _payment, receipt = await _receipted(client)
    detail = await _detail(client, headers, receipt["id"])
    line = detail["lines"][0]
    assert line["settlement_id"] == settlement["id"]
    assert line["settlement_number"] == settlement["settlement_number"]
    assert line["center_id"] == center["id"]
    assert Decimal(line["net_amount"]) == FULL
    assert Decimal(line["amount_paid"]) == FULL
    assert line["period_from"] == "2026-10-01" and line["period_to"] == "2026-10-31"


async def test_receipt_never_modifies_the_payment_or_settlement(client):
    headers, _center, _supplier, settlement, payment, _receipt = await _receipted(client)
    after_payment = (await client.get(f"/v1/payments/{payment['id']}", headers=headers)).json()[
        "payment"
    ]
    assert after_payment["status"] == "completed"
    assert Decimal(after_payment["amount"]) == FULL
    after_settlement = (
        await client.get(f"/v1/settlements/{settlement['id']}", headers=headers)
    ).json()["settlement"]
    assert after_settlement["status"] == "finalized"
    assert after_settlement["finalized_at"] == settlement["finalized_at"]


# --- multiple settlement lines ----------------------------------------------


async def test_receipt_covers_multiple_settlements(client):
    headers, center, supplier, october = await _payable(client)
    november = await _second_settlement(client, headers, center, supplier)
    payment = (
        await _create_payment(
            client,
            headers,
            supplier["id"],
            [{"settlement_id": october["id"]}, {"settlement_id": november["id"]}],
        )
    ).json()
    await _complete_payment(client, headers, payment["id"])
    await _runner().run_once()

    page = (await client.get("/v1/receipts", headers=headers)).json()
    assert page["total"] == 1  # one payment, one receipt
    receipt = page["items"][0]
    assert receipt["line_count"] == 2
    detail = await _detail(client, headers, receipt["id"])
    numbers = {line["settlement_number"] for line in detail["lines"]}
    assert numbers == {october["settlement_number"], november["settlement_number"]}
    # Receipt gross is the sum of the settlements it covers.
    expected_gross = Decimal(october["gross_amount"]) + Decimal(november["gross_amount"])
    assert Decimal(receipt["gross_amount"]) == expected_gross
    assert Decimal(receipt["net_amount"]) == Decimal(payment["amount"])


async def test_partial_payment_receipt_shows_paid_below_the_settlement_total(client):
    """A receipt proves what was PAID; the line still shows what was owed."""
    headers, _center, _supplier, settlement = await _payable(client)
    payment = await _pay(client, headers, settlement, amount="3000.00")
    await _complete_payment(client, headers, payment["id"])
    await _runner().run_once()

    receipt = (await client.get("/v1/receipts", headers=headers)).json()["items"][0]
    assert Decimal(receipt["net_amount"]) == Decimal("3000.00")
    assert Decimal(receipt["gross_amount"]) == FULL
    line = (await _detail(client, headers, receipt["id"]))["lines"][0]
    assert Decimal(line["amount_paid"]) == Decimal("3000.00")
    assert Decimal(line["net_amount"]) == FULL


async def test_two_payments_on_one_settlement_produce_two_receipts(client):
    headers, _center, _supplier, settlement = await _payable(client)
    first = await _pay(client, headers, settlement, amount="3000.00")
    await _complete_payment(client, headers, first["id"], reference="A")
    second = await _pay(client, headers, settlement)
    await _complete_payment(client, headers, second["id"], reference="B")
    await _runner().run_once()

    page = (await client.get("/v1/receipts", headers=headers)).json()
    assert page["total"] == 2
    assert {r["payment_id"] for r in page["items"]} == {first["id"], second["id"]}


# --- duplicate prevention & numbering ---------------------------------------


async def test_one_payment_generates_exactly_one_receipt(client):
    headers, _center, _supplier, _settlement, _payment, _receipt = await _receipted(client)
    runner = _runner()
    await runner.run_once()
    await runner.run_once()  # nothing new to consume
    assert len(await _receipts()) == 1
    assert (await client.get("/v1/receipts", headers=headers)).json()["total"] == 1


async def test_consumer_replay_does_not_mint_a_second_receipt(client):
    """Rewinding the consumer must not hand a farmer two receipts for one
    payment — the (tenant, payment) constraint holds under replay."""
    from platform_core.core import db
    from platform_core.modules.event_relay.models import ConsumerCursor

    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    async with db.get_session_factory()() as s:
        for cursor in (await s.scalars(select(ConsumerCursor))).all():
            cursor.position_created_at = None
            cursor.position_event_id = None
        await s.commit()
    await _runner().run_once()

    page = (await client.get("/v1/receipts", headers=headers)).json()
    assert page["total"] == 1
    assert page["items"][0]["id"] == receipt["id"]  # the same artifact, not a twin


async def test_receipt_numbers_are_unique_within_a_tenant(client):
    headers, center, supplier, october = await _payable(client)
    november = await _second_settlement(client, headers, center, supplier)
    for settlement in (october, november):
        payment = await _pay(client, headers, settlement)
        await _complete_payment(client, headers, payment["id"])
    await _runner().run_once()

    page = (await client.get("/v1/receipts?limit=50", headers=headers)).json()
    numbers = [r["receipt_number"] for r in page["items"]]
    assert len(numbers) == 2 and len(set(numbers)) == 2
    assert all(n.startswith("RCP-") for n in numbers)


# --- immutability & lifecycle ------------------------------------------------


async def test_lifecycle_generated_delivered_archived(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    delivered = (await client.post(f"/v1/receipts/{receipt['id']}/deliver", headers=headers)).json()
    assert delivered["status"] == "delivered" and delivered["delivered_at"] is not None
    archived = (await client.post(f"/v1/receipts/{receipt['id']}/archive", headers=headers)).json()
    assert archived["status"] == "archived" and archived["archived_at"] is not None


async def test_a_receipt_can_be_archived_without_delivery(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    r = await client.post(f"/v1/receipts/{receipt['id']}/archive", headers=headers)
    assert r.status_code == 200 and r.json()["status"] == "archived"


async def test_archived_receipts_are_terminal_but_queryable(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    await client.post(f"/v1/receipts/{receipt['id']}/archive", headers=headers)
    for action in ("deliver", "archive"):
        r = await client.post(f"/v1/receipts/{receipt['id']}/{action}", headers=headers)
        assert r.status_code == 409, action
        assert "archived receipts are terminal" in r.text
    # Still fully readable, listed, and renderable — nothing is deleted.
    detail = await _detail(client, headers, receipt["id"])
    assert detail["receipt"]["status"] == "archived"
    listed = (await client.get("/v1/receipts?status=archived", headers=headers)).json()
    assert listed["total"] == 1
    rendered = await client.get(f"/v1/receipts/{receipt['id']}/render", headers=headers)
    assert rendered.status_code == 200


async def test_delivered_receipt_cannot_go_back_to_generated(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    await client.post(f"/v1/receipts/{receipt['id']}/deliver", headers=headers)
    r = await client.post(f"/v1/receipts/{receipt['id']}/deliver", headers=headers)
    assert r.status_code == 409
    assert "cannot become delivered" in r.text


async def test_receipt_content_is_frozen_after_generation(client):
    """The artifact keeps the world as it was: renaming the supplier later
    must not rewrite a receipt already issued."""
    headers, _center, supplier, _settlement, _payment, receipt = await _receipted(client)
    r = await client.patch(
        f"/v1/suppliers/{supplier['id']}",
        json={"full_name": "Renamed Afterwards"},
        headers=headers,
    )
    assert r.status_code in (200, 404, 405), r.text
    after = await _detail(client, headers, receipt["id"])
    assert after["receipt"]["supplier_name"] == "Amina Njoroge"


async def test_no_delete_or_edit_endpoint_exists(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    for method in ("delete", "put", "patch"):
        r = await getattr(client, method)(
            f"/v1/receipts/{receipt['id']}",
            headers=headers,
            **({"json": {}} if method != "delete" else {}),
        )
        assert r.status_code == 405, method


async def test_concurrent_delivery_only_succeeds_once(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    first = await client.post(f"/v1/receipts/{receipt['id']}/deliver", headers=headers)
    second = await client.post(f"/v1/receipts/{receipt['id']}/deliver", headers=headers)
    assert first.status_code == 200 and second.status_code == 409


# --- rendering abstraction ---------------------------------------------------


async def test_json_rendering_is_the_canonical_artifact(client):
    import json

    headers, _center, _supplier, settlement, _payment, receipt = await _receipted(client)
    body = (
        await client.get(f"/v1/receipts/{receipt['id']}/render?format=json", headers=headers)
    ).json()
    assert body["format"] == "json" and body["content_type"] == "application/json"
    assert body["filename"] == f"{receipt['receipt_number']}.json"
    assert body["placeholder"] is False
    payload = json.loads(body["body"])
    assert payload["receipt_number"] == receipt["receipt_number"]
    assert payload["net_amount"] == str(FULL)
    assert payload["lines"][0]["settlement_number"] == settlement["settlement_number"]


async def test_html_rendering_is_self_contained(client):
    headers, _center, _supplier, settlement, _payment, receipt = await _receipted(client)
    body = (
        await client.get(f"/v1/receipts/{receipt['id']}/render?format=html", headers=headers)
    ).json()
    assert body["format"] == "html" and body["content_type"].startswith("text/html")
    html = body["body"]
    assert receipt["receipt_number"] in html
    assert "Amina Njoroge" in html and settlement["settlement_number"] in html
    assert str(FULL) in html
    # A village printer has no connectivity: nothing may be fetched.
    for external in ("http://", "https://", "<script"):
        assert external not in html


async def test_pdf_is_a_real_document(client):
    """PROD-001 replaced RCP-001's placeholder with a real PDF writer.

    This test previously asserted the OPPOSITE — that the artifact announced
    itself as a stand-in — which was correct while the scope wall forbade a PDF
    engine and is exactly the assertion that must now invert. Structural depth
    lives in `test_receipt_pdf.py`; this is the end-to-end shape.
    """
    import base64

    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    body = (
        await client.get(f"/v1/receipts/{receipt['id']}/render?format=pdf", headers=headers)
    ).json()
    assert body["format"] == "pdf" and body["placeholder"] is False
    assert body["encoding"] == "base64"
    assert base64.b64decode(body["body"]).startswith(b"%PDF-1.4")
    assert receipt["receipt_number"].encode() in base64.b64decode(body["body"])


async def test_rendering_is_deterministic(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)

    async def render():
        return (
            await client.get(f"/v1/receipts/{receipt['id']}/render?format=html", headers=headers)
        ).json()["body"]

    assert await render() == await render()  # frozen record -> identical artifact


async def test_unknown_format_is_rejected(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    r = await client.get(f"/v1/receipts/{receipt['id']}/render?format=xlsx", headers=headers)
    assert r.status_code == 422
    assert "no renderer for format" in r.text


async def test_renderer_is_swappable(client, renderer_guard):
    """The abstraction is the point: a deployment registers its own engine."""
    from platform_core.modules.receipt.rendering import RenderedReceipt

    class _FakePdf:
        name = "fake-pdf"
        format = "pdf"
        content_type = "application/pdf"

        def render(self, receipt):
            return RenderedReceipt(
                format="pdf",
                content_type="application/pdf",
                filename=f"{receipt['receipt_number']}.pdf",
                body="%PDF-1.7 real engine",
            )

    renderer_guard.register_renderer(_FakePdf())
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    body = (
        await client.get(f"/v1/receipts/{receipt['id']}/render?format=pdf", headers=headers)
    ).json()
    assert body["content_type"] == "application/pdf"
    assert body["body"].startswith("%PDF-1.7")
    assert body["placeholder"] is False


async def test_download_serves_a_file(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    r = await client.get(f"/v1/receipts/{receipt['id']}/download?format=html", headers=headers)
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("text/html")
    assert receipt["receipt_number"] in r.headers["content-disposition"]
    assert receipt["receipt_number"] in r.text


async def test_download_defaults_to_a_real_pdf(client):
    """A download serves the renderer's own bytes.

    PROD-001: this route used to call `render()`, whose body is base64 because
    its return type is a JSON view — so `?format=pdf` served base64 TEXT under
    `application/pdf` and no reader could open it. `render_artifact()` exists
    to keep the two callers apart.
    """
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    r = await client.get(f"/v1/receipts/{receipt['id']}/download", headers=headers)
    assert r.status_code == 200
    assert r.headers["content-type"] == "application/pdf"
    assert r.content.startswith(b"%PDF-1.4")
    assert r.headers["content-disposition"].endswith(f'"{receipt["receipt_number"]}.pdf"')


async def test_metadata_reports_the_available_formats(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    detail = await _detail(client, headers, receipt["id"])
    assert set(detail["metadata"]["available_formats"]) >= {"json", "html", "pdf"}
    assert detail["metadata"]["version"] == 1
    assert detail["metadata"]["render_format"] == "json"
    assert detail["metadata"]["delivered_at"] is None


async def test_reference_traces_back_to_the_source_event(client):
    headers, center, _supplier, settlement, payment, receipt = await _receipted(client)
    reference = (await _detail(client, headers, receipt["id"]))["reference"]
    assert reference["payment_id"] == payment["id"]
    assert reference["payment_number"] == payment["payment_number"]
    assert reference["payment_reference"] == "MPESA-77"
    assert reference["settlement_ids"] == [settlement["id"]]
    assert reference["settlement_numbers"] == [settlement["settlement_number"]]
    assert reference["center_ids"] == [center["id"]]
    assert reference["source_event_id"] is not None


# --- events ------------------------------------------------------------------


async def test_generation_emits_its_event(client, bus):
    headers, _center, supplier, _settlement, _payment, receipt = await _receipted(client)
    generated = [e for e in bus.published if e.type == "receipt.generated.v1"]
    assert len(generated) == 1
    event = generated[0]
    assert event.data["receipt_number"] == receipt["receipt_number"]
    assert event.data["supplier_id"] == supplier["id"]
    assert event.data["amount"] == str(FULL)
    assert event.data["currency"] == "KES"
    assert event.aggregate_type == "receipt"
    assert event.tenant_id is not None  # consumers depend on this
    assert headers


async def test_lifecycle_emits_delivered_and_archived(client, bus):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    await client.post(f"/v1/receipts/{receipt['id']}/deliver", headers=headers)
    await client.post(f"/v1/receipts/{receipt['id']}/archive", headers=headers)
    types = [e.type for e in bus.published if e.type.startswith("receipt.")]
    assert "receipt.delivered.v1" in types
    assert "receipt.archived.v1" in types


# --- history, search, pagination ---------------------------------------------


async def test_history_search_by_number_supplier_and_reference(client):
    headers, _center, _supplier, _settlement, payment, receipt = await _receipted(client)

    async def search(query):
        return (await client.get(f"/v1/receipts?q={query}", headers=headers)).json()

    assert (await search(receipt["receipt_number"][4:]))["total"] == 1
    assert (await search(payment["payment_number"][4:]))["total"] == 1
    assert (await search("amina"))["total"] == 1
    assert (await search("mpesa-77"))["total"] == 1
    assert (await search("nothing-matches"))["total"] == 0


async def test_history_filters_by_status_and_payment(client):
    headers, _center, _supplier, _settlement, payment, receipt = await _receipted(client)
    assert (await client.get("/v1/receipts?status=generated", headers=headers)).json()["total"] == 1
    assert (await client.get("/v1/receipts?status=archived", headers=headers)).json()["total"] == 0
    by_payment = (
        await client.get(f"/v1/receipts?payment_id={payment['id']}", headers=headers)
    ).json()
    assert by_payment["total"] == 1 and by_payment["items"][0]["id"] == receipt["id"]


async def test_history_paginates_newest_first(client):
    headers, center, supplier, october = await _payable(client)
    november = await _second_settlement(client, headers, center, supplier)
    for settlement in (october, november):
        payment = await _pay(client, headers, settlement)
        await _complete_payment(client, headers, payment["id"])
    await _runner().run_once()

    page = (await client.get("/v1/receipts?limit=1&offset=0", headers=headers)).json()
    assert page["total"] == 2 and len(page["items"]) == 1
    assert page["limit"] == 1 and page["offset"] == 0
    second = (await client.get("/v1/receipts?limit=1&offset=1", headers=headers)).json()
    assert second["items"][0]["id"] != page["items"][0]["id"]


async def test_unknown_receipt_is_404(client):
    headers, _center, _supplier, _settlement, _payment, _receipt = await _receipted(client)
    assert (await client.get(f"/v1/receipts/{uuid.uuid4()}", headers=headers)).status_code == 404
    assert (
        await client.get(f"/v1/receipts/{uuid.uuid4()}/render", headers=headers)
    ).status_code == 404


# --- notification integration -------------------------------------------------


async def test_notifications_consume_receipt_generated(client):
    """RCP-001 closes the loop the same way PAY-001 did: the receipt event
    drives an SMS, and the receipt module knows nothing about messaging."""
    from platform_core.core import db
    from platform_core.modules.notification.models import Notification

    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    # A second pass consumes the receipt.generated.v1 the first pass produced.
    await _runner().run_once()

    async with db.get_session_factory()() as s:
        notifications = list(
            (
                await s.scalars(
                    select(Notification).where(Notification.template_key == "receipt_available")
                )
            ).all()
        )
    assert len(notifications) == 1
    assert receipt["receipt_number"] in notifications[0].rendered_text
    assert str(FULL) in notifications[0].rendered_text
    assert notifications[0].recipient == "+254700000001"
    assert headers


# --- permissions --------------------------------------------------------------


async def test_receipt_api_requires_authentication(client):
    assert (await client.get("/v1/receipts")).status_code in (401, 403)


async def test_user_without_permission_is_forbidden(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    _, outsider = await register_and_login(client, "receipt-outsider@example.com")
    for path in ("/v1/receipts", f"/v1/receipts/{receipt['id']}"):
        assert (await client.get(path, headers=outsider)).status_code == 403
    r = await client.post(f"/v1/receipts/{receipt['id']}/archive", headers=outsider)
    assert r.status_code == 403
    assert headers


async def test_viewer_reads_and_downloads_but_cannot_manage(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    viewer = await _viewer(client, headers)
    assert (await client.get("/v1/receipts", headers=viewer)).status_code == 200
    assert (await client.get(f"/v1/receipts/{receipt['id']}", headers=viewer)).status_code == 200
    assert (
        await client.get(f"/v1/receipts/{receipt['id']}/download", headers=viewer)
    ).status_code == 200
    for action in ("deliver", "archive"):
        r = await client.post(f"/v1/receipts/{receipt['id']}/{action}", headers=viewer)
        assert r.status_code == 403, action


async def test_all_receipt_permissions_are_registered(client):
    from platform_core.modules.authz.permissions import PERMISSIONS

    for key in ("receipt.read", "receipt.manage", "receipt.download"):
        assert key in PERMISSIONS


# --- tenant isolation ---------------------------------------------------------


async def test_receipts_are_invisible_across_tenants(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    other = await _second_tenant(client)
    assert (await client.get("/v1/receipts", headers=other)).json()["total"] == 0
    for path in (
        f"/v1/receipts/{receipt['id']}",
        f"/v1/receipts/{receipt['id']}/render",
        f"/v1/receipts/{receipt['id']}/download",
    ):
        assert (await client.get(path, headers=other)).status_code == 404, path
    assert headers


async def test_another_tenant_cannot_change_a_receipt_lifecycle(client):
    headers, _center, _supplier, _settlement, _payment, receipt = await _receipted(client)
    other = await _second_tenant(client)
    for action in ("deliver", "archive"):
        r = await client.post(f"/v1/receipts/{receipt['id']}/{action}", headers=other)
        assert r.status_code == 404, action
    assert headers
