import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'api.dart';

/// Receipt history — RCP-001.
///
/// The artifact a farmer asks for at the collection center: "show me proof I
/// was paid". Receipts are generated by the platform from completed payments,
/// so the app only reads, previews, and hands over a copy.
class ReceiptHistoryScreen extends StatefulWidget {
  const ReceiptHistoryScreen({super.key, required this.client});

  final ApiClient client;

  @override
  State<ReceiptHistoryScreen> createState() => _ReceiptHistoryScreenState();
}

class _ReceiptHistoryScreenState extends State<ReceiptHistoryScreen> {
  static const pageSize = 20;
  static const statuses = ['', 'generated', 'delivered', 'archived'];

  final _search = TextEditingController();
  ReceiptPageResult? _page;
  String _status = '';
  int _offset = 0;
  String? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _search.dispose();
    super.dispose();
  }

  Future<void> _load() async {
    try {
      final page = await widget.client.listReceipts(
        query: _search.text.trim(),
        status: _status,
        limit: pageSize,
        offset: _offset,
      );
      if (!mounted) return;
      setState(() {
        _page = page;
        _error = null;
      });
    } on ApiException catch (e) {
      if (mounted) setState(() => _error = e.detail);
    }
  }

  @override
  Widget build(BuildContext context) {
    final page = _page;
    final scheme = Theme.of(context).colorScheme;
    return Scaffold(
      appBar: AppBar(title: const Text('Receipts')),
      body: RefreshIndicator(
        onRefresh: _load,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            TextField(
              controller: _search,
              decoration: const InputDecoration(
                prefixIcon: Icon(Icons.search),
                hintText: 'Search receipt, payment or supplier',
              ),
              onSubmitted: (_) {
                _offset = 0;
                _load();
              },
            ),
            const SizedBox(height: 12),
            SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(
                children: statuses
                    .map(
                      (s) => Padding(
                        padding: const EdgeInsets.only(right: 8),
                        child: ChoiceChip(
                          label: Text(s.isEmpty ? 'All' : s),
                          selected: _status == s,
                          onSelected: (_) {
                            setState(() {
                              _status = s;
                              _offset = 0;
                            });
                            _load();
                          },
                        ),
                      ),
                    )
                    .toList(),
              ),
            ),
            const SizedBox(height: 12),
            if (_error != null)
              Text(_error!, style: TextStyle(color: scheme.error)),
            if (page == null && _error == null)
              const Padding(
                padding: EdgeInsets.all(32),
                child: Center(child: CircularProgressIndicator()),
              ),
            if (page != null && page.items.isEmpty)
              const Padding(
                padding: EdgeInsets.all(32),
                child: Center(child: Text('No receipts yet.')),
              ),
            if (page != null)
              ...page.items.map(
                (r) => Card(
                  child: ListTile(
                    leading: const Icon(Icons.receipt_long_outlined),
                    title: Text('${r.netAmount} ${r.currency}'),
                    subtitle: Text(
                      '${r.number} · ${r.supplierName}\n'
                      '${r.lineCount} settlement(s) · '
                      '${r.generatedAt.replaceFirst('T', ' ').split('.').first}',
                    ),
                    isThreeLine: true,
                    trailing: Chip(
                      label: Text(r.status),
                      visualDensity: VisualDensity.compact,
                    ),
                    onTap: () => Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (_) => ReceiptDetailScreen(
                          client: widget.client,
                          receiptId: r.id,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            if (page != null && page.total > pageSize)
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  TextButton(
                    onPressed: _offset == 0
                        ? null
                        : () {
                            _offset = (_offset - pageSize).clamp(0, 1 << 30);
                            _load();
                          },
                    child: const Text('Previous'),
                  ),
                  Text(
                    '${(_offset ~/ pageSize) + 1} / '
                    '${(page.total / pageSize).ceil()}',
                  ),
                  TextButton(
                    onPressed: _offset + pageSize >= page.total
                        ? null
                        : () {
                            _offset += pageSize;
                            _load();
                          },
                    child: const Text('Next'),
                  ),
                ],
              ),
          ],
        ),
      ),
    );
  }
}

/// Receipt detail with a rendered preview and a download placeholder.
class ReceiptDetailScreen extends StatefulWidget {
  const ReceiptDetailScreen({
    super.key,
    required this.client,
    required this.receiptId,
  });

  final ApiClient client;
  final String receiptId;

  @override
  State<ReceiptDetailScreen> createState() => _ReceiptDetailScreenState();
}

class _ReceiptDetailScreenState extends State<ReceiptDetailScreen> {
  ReceiptDetailResult? _detail;
  RenderedReceipt? _preview;
  String _format = 'pdf';
  String? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    try {
      final detail = await widget.client.receiptDetail(widget.receiptId);
      if (!mounted) return;
      setState(() {
        _detail = detail;
        _error = null;
      });
      await _render(_format);
    } on ApiException catch (e) {
      if (mounted) setState(() => _error = e.detail);
    }
  }

  Future<void> _render(String format) async {
    try {
      final preview = await widget.client.renderReceipt(
        widget.receiptId,
        format,
      );
      if (!mounted) return;
      setState(() {
        _preview = preview;
        _format = format;
        _error = null;
      });
    } on ApiException catch (e) {
      if (mounted) setState(() => _error = e.detail);
    }
  }

  /// Download placeholder: the device has no file-save capability wired yet,
  /// so the artifact is copied to the clipboard and the user is told plainly.
  Future<void> _download() async {
    final preview = _preview;
    if (preview == null) return;
    await Clipboard.setData(ClipboardData(text: preview.body));
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(
          preview.placeholder
              ? '${preview.filename} copied — placeholder artifact, no PDF engine yet'
              : '${preview.filename} copied to the clipboard',
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final detail = _detail;
    final r = detail?.receipt;
    final preview = _preview;
    return Scaffold(
      appBar: AppBar(title: Text(r?.number ?? 'Receipt')),
      body: detail == null || r == null
          ? Center(
              child: _error != null
                  ? Text(_error!)
                  : const CircularProgressIndicator(),
            )
          : ListView(
              padding: const EdgeInsets.all(16),
              children: [
                Card(
                  child: ListTile(
                    title: Text('${r.netAmount} ${r.currency}'),
                    subtitle: Text(
                      '${r.supplierName} (${r.supplierCode})\n'
                      'Payment ${r.paymentNumber}'
                      '${r.paymentReference != null ? ' · ref ${r.paymentReference}' : ''}',
                    ),
                    isThreeLine: true,
                    trailing: Chip(
                      label: Text(r.status),
                      visualDensity: VisualDensity.compact,
                    ),
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Settlements (${detail.lines.length})',
                  style: Theme.of(context).textTheme.titleMedium,
                ),
                ...detail.lines.map(
                  (line) => Card(
                    child: ListTile(
                      dense: true,
                      title: Text(line.settlementNumber),
                      subtitle: line.periodFrom != null
                          ? Text('${line.periodFrom} to ${line.periodTo}')
                          : null,
                      trailing: Text('${line.amountPaid} ${r.currency}'),
                    ),
                  ),
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    Text(
                      'Preview',
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                    const SizedBox(width: 12),
                    ...detail.availableFormats.map(
                      (f) => Padding(
                        padding: const EdgeInsets.only(right: 8),
                        child: ChoiceChip(
                          label: Text(f.toUpperCase()),
                          selected: _format == f,
                          onSelected: (_) => _render(f),
                        ),
                      ),
                    ),
                  ],
                ),
                if (preview != null) ...[
                  if (preview.placeholder)
                    Card(
                      color: Theme.of(
                        context,
                      ).colorScheme.surfaceContainerHighest,
                      child: const ListTile(
                        dense: true,
                        leading: Icon(Icons.info_outline),
                        title: Text('Placeholder artifact'),
                        subtitle: Text('No PDF engine is integrated yet.'),
                      ),
                    ),
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(12),
                      child: SelectableText(
                        preview.body,
                        style: const TextStyle(
                          fontFamily: 'monospace',
                          fontSize: 11,
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8),
                    child: FilledButton.icon(
                      onPressed: _download,
                      icon: const Icon(Icons.download_outlined),
                      label: Text('Download ${preview.filename}'),
                    ),
                  ),
                ],
                if (_error != null)
                  Text(
                    _error!,
                    style: TextStyle(
                      color: Theme.of(context).colorScheme.error,
                    ),
                  ),
              ],
            ),
    );
  }
}
