import { cn } from "@/lib/utils";

/**
 * The Lacteva mark (LACTEVA-BRAND-002; decision D-2).
 *
 * A milk drop in a rounded dairy field — the same concept the interim mark
 * carried, redrawn. The geometry is generated by `tools/brand/mark.py` and
 * appears here as literal path data because an inline SVG cannot import from
 * a Python module; `tools/brand/check_inline.py` fails the build if this copy
 * and the generator ever disagree, which is how the three hand-drawn cousins
 * that existed before this are prevented from coming back.
 *
 * This component remains the single swap point for the lockup.
 */

/** Generated — do not edit by hand. See tools/brand/mark.py. */
export const MARK_PATH =
  "M30.69 13.229C32 11.1 32 11.1 33.31 13.229C35.613 19.1 38.866 24.386 43.071 29.085C46.426 34.537 45.314 41.619 40.449 45.78C35.585 49.94 28.415 49.94 23.551 45.78C18.686 41.619 17.574 34.537 20.929 29.085C25.134 24.386 28.387 19.1 30.69 13.229Z";

export function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 64 64"
      aria-hidden="true"
      className={cn("size-8", className)}
    >
      <rect width="64" height="64" rx="17" className="fill-primary" />
      <path d={MARK_PATH} className="fill-primary-foreground" />
    </svg>
  );
}

/** The mark alone, taking its colour from the text around it. */
export function LogoDrop({ className }: { className?: string }) {
  return (
    <svg viewBox="19 11.63 26 37.27" aria-hidden="true" className={cn("size-4", className)}>
      <path d={MARK_PATH} fill="currentColor" />
    </svg>
  );
}

export function Wordmark({ className }: { className?: string }) {
  return (
    // Text color inherits, so a dark band recolors the wordmark by setting
    // its own text class; `text-foreground` here is only the default.
    <span
      className={cn("flex items-center gap-2.5 text-foreground", className)}
    >
      <LogoMark />
      <span className="text-lg font-semibold tracking-tight">Lacteva</span>
    </span>
  );
}
